//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatBot_Net5.Culture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Msgs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Msgs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatBot_Net5.Culture.Msgs", typeof(Msgs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addcommand.
        /// </summary>
        internal static string addcommand {
            get {
                return ResourceManager.GetString("addcommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto-hosting.
        /// </summary>
        internal static string autohost {
            get {
                return ResourceManager.GetString("autohost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bot.
        /// </summary>
        internal static string bot {
            get {
                return ResourceManager.GetString("bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commands.
        /// </summary>
        internal static string commands {
            get {
                return ResourceManager.GetString("commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @everyone.
        /// </summary>
        internal static string everyone {
            get {
                return ResourceManager.GetString("everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied value {0} is not included within the acceptable list: {1}.
        /// </summary>
        internal static string ExceptionArgument {
            get {
                return ResourceManager.GetString("ExceptionArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;No permission to invoke this command.&quot;.
        /// </summary>
        internal static string ExceptionInvalidCommand {
            get {
                return ResourceManager.GetString("ExceptionInvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The command {0} is configured for {1}, but can only perform {2}&quot;.
        /// </summary>
        internal static string ExceptionInvalidComUsage {
            get {
                return ResourceManager.GetString("ExceptionInvalidComUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not found..
        /// </summary>
        internal static string ExceptionInvalidOpCommand {
            get {
                return ResourceManager.GetString("ExceptionInvalidOpCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field not specified..
        /// </summary>
        internal static string ExceptionInvalidOperationField {
            get {
                return ResourceManager.GetString("ExceptionInvalidOperationField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table not specified..
        /// </summary>
        internal static string ExceptionInvalidOperationTable {
            get {
                return ResourceManager.GetString("ExceptionInvalidOperationTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to followage.
        /// </summary>
        internal static string followage {
            get {
                return ResourceManager.GetString("followage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to permits distinguishing if the channel is hosted or autohosted.
        /// </summary>
        internal static string Helpautohost {
            get {
                return ResourceManager.GetString("Helpautohost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message displayed when a user hosts the channel. Currently only supported when the bot&apos;s user name is the same as the streamer&apos;s user name..
        /// </summary>
        internal static string HelpBeingHosted {
            get {
                return ResourceManager.GetString("HelpBeingHosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The thank you message when a user donates bits to the channel..
        /// </summary>
        internal static string HelpBits {
            get {
                return ResourceManager.GetString("HelpBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current category.
        /// </summary>
        internal static string Helpcategory {
            get {
                return ResourceManager.GetString("Helpcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you message for someone gifting subscription(s) to the channel.
        /// </summary>
        internal static string HelpCommunitySubs {
            get {
                return ResourceManager.GetString("HelpCommunitySubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the number of donated subscriptions with tier plan: e.g. 5 Tier 1 Subscriptions.
        /// </summary>
        internal static string Helpcount {
            get {
                return ResourceManager.GetString("Helpcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the current date in your timezone.
        /// </summary>
        internal static string Helpdate {
            get {
                return ResourceManager.GetString("Helpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When included, will replace &apos;#everyone&apos; with either (true) &apos;@everyone&apos; or (false) &apos;&lt;blank&gt;&apos; depending on whether the &apos;AddEveryone&apos; is checked (true) or unchecked (false) alongside the Discord Server link..
        /// </summary>
        internal static string Helpeveryone {
            get {
                return ResourceManager.GetString("Helpeveryone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome message for new follower to the channel.
        /// </summary>
        internal static string HelpFollow {
            get {
                return ResourceManager.GetString("HelpFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you message for someone gifting subscription(s) to a user.
        /// </summary>
        internal static string HelpGiftSub {
            get {
                return ResourceManager.GetString("HelpGiftSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently not used..
        /// </summary>
        internal static string HelpJoinChannel {
            get {
                return ResourceManager.GetString("HelpJoinChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently not used..
        /// </summary>
        internal static string HelpLeaveChannel {
            get {
                return ResourceManager.GetString("HelpLeaveChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message to send out to social media when the channel goes live..
        /// </summary>
        internal static string HelpLive {
            get {
                return ResourceManager.GetString("HelpLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how many months subscribed this time.
        /// </summary>
        internal static string Helpmonths {
            get {
                return ResourceManager.GetString("Helpmonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The results of the command query will go here..
        /// </summary>
        internal static string Helpquery {
            get {
                return ResourceManager.GetString("Helpquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The welcome and thank you message when a user raids the channel.
        /// </summary>
        internal static string HelpRaid {
            get {
                return ResourceManager.GetString("HelpRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently not used..
        /// </summary>
        internal static string HelpRandom {
            get {
                return ResourceManager.GetString("HelpRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the user who received the gifted subscription.
        /// </summary>
        internal static string Helpreceiveuser {
            get {
                return ResourceManager.GetString("Helpreceiveuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently not used..
        /// </summary>
        internal static string HelpRespond {
            get {
                return ResourceManager.GetString("HelpRespond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The thank you message when a user resubscribes to the channel..
        /// </summary>
        internal static string HelpResubscribe {
            get {
                return ResourceManager.GetString("HelpResubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message to provide when a user/viewer is returning to the stream..
        /// </summary>
        internal static string HelpReturnUserJoined {
            get {
                return ResourceManager.GetString("HelpReturnUserJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current sub streak months, depends on user preference to share.
        /// </summary>
        internal static string Helpstreak {
            get {
                return ResourceManager.GetString("Helpstreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how many overall months subscribed.
        /// </summary>
        internal static string Helpsubmonths {
            get {
                return ResourceManager.GetString("Helpsubmonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the subscription plan.
        /// </summary>
        internal static string Helpsubplan {
            get {
                return ResourceManager.GetString("Helpsubplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the subscription plan name.
        /// </summary>
        internal static string Helpsubplanname {
            get {
                return ResourceManager.GetString("Helpsubplanname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The thank you message when a user subscribes to the channel..
        /// </summary>
        internal static string HelpSubscribe {
            get {
                return ResourceManager.GetString("HelpSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message to provide when user/viewer is a follower to the stream and supporting the channel..
        /// </summary>
        internal static string HelpSupporterJoined {
            get {
                return ResourceManager.GetString("HelpSupporterJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the current time in your timezone.
        /// </summary>
        internal static string Helptime {
            get {
                return ResourceManager.GetString("Helptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current live stream title.
        /// </summary>
        internal static string Helptitle {
            get {
                return ResourceManager.GetString("Helptitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specific detailed message the bot chats upon joining the channel..
        /// </summary>
        internal static string HelpTwineBotInfo {
            get {
                return ResourceManager.GetString("HelpTwineBotInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify user&apos;s name, will add Twitch&apos;s URL prefix.
        /// </summary>
        internal static string Helpurl {
            get {
                return ResourceManager.GetString("Helpurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display name of the user sending action.
        /// </summary>
        internal static string Helpuser {
            get {
                return ResourceManager.GetString("Helpuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message the bot uses to welcome users to the channel. See options for &quot;no welcome&quot;, &quot;welcome when joined&quot;, or &quot;welcome when user chats&quot;..
        /// </summary>
        internal static string HelpUserJoined {
            get {
                return ResourceManager.GetString("HelpUserJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display name of the user sending action.
        /// </summary>
        internal static string Helpviewers {
            get {
                return ResourceManager.GetString("Helpviewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hosting.
        /// </summary>
        internal static string host {
            get {
                return ResourceManager.GetString("host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to join.
        /// </summary>
        internal static string join {
            get {
                return ResourceManager.GetString("join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently not used..
        /// </summary>
        internal static string JoinChannel {
            get {
                return ResourceManager.GetString("JoinChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not found..
        /// </summary>
        internal static string KeyNotFoundException {
            get {
                return ResourceManager.GetString("KeyNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leave.
        /// </summary>
        internal static string leave {
            get {
                return ResourceManager.GetString("leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently not used..
        /// </summary>
        internal static string LeaveChannel {
            get {
                return ResourceManager.GetString("LeaveChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lurk.
        /// </summary>
        internal static string lurk {
            get {
                return ResourceManager.GetString("lurk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command added.
        /// </summary>
        internal static string Msgaddcommand {
            get {
                return ResourceManager.GetString("Msgaddcommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string MsgAllCateogry {
            get {
                return ResourceManager.GetString("MsgAllCateogry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for #autohost this channel!.
        /// </summary>
        internal static string MsgBeingHosted {
            get {
                return ResourceManager.GetString("MsgBeingHosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for giving #bits!.
        /// </summary>
        internal static string MsgBits {
            get {
                return ResourceManager.GetString("MsgBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twine ChatBot written by WrithemTwine, https://github.com/WrithemTwine/TwineChatBot/.
        /// </summary>
        internal static string Msgbot {
            get {
                return ResourceManager.GetString("Msgbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of commands: #query.
        /// </summary>
        internal static string Msgcommands {
            get {
                return ResourceManager.GetString("Msgcommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for giving #count to the community!.
        /// </summary>
        internal static string MsgCommunitySubs {
            get {
                return ResourceManager.GetString("MsgCommunitySubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data not found..
        /// </summary>
        internal static string MsgDataNotFound {
            get {
                return ResourceManager.GetString("MsgDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are enjoying the content, please hit that follow button!.
        /// </summary>
        internal static string Msgfollow {
            get {
                return ResourceManager.GetString("Msgfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #user has followed for #query!.
        /// </summary>
        internal static string Msgfollowage {
            get {
                return ResourceManager.GetString("Msgfollowage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for gifting a #subplan subscription to #receiveuser!.
        /// </summary>
        internal static string MsgGiftSub {
            get {
                return ResourceManager.GetString("MsgGiftSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message isn&apos;t used in response..
        /// </summary>
        internal static string Msgjoin {
            get {
                return ResourceManager.GetString("Msgjoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message isn&apos;t used in response..
        /// </summary>
        internal static string Msgleave {
            get {
                return ResourceManager.GetString("Msgleave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #everyone #user is now live streaming #category - #title! Come join and say hi at: #url.
        /// </summary>
        internal static string MsgLive {
            get {
                return ResourceManager.GetString("MsgLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #user is now lurking. See you soon!.
        /// </summary>
        internal static string Msglurk {
            get {
                return ResourceManager.GetString("Msglurk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for the follow!.
        /// </summary>
        internal static string MsgNewFollow {
            get {
                return ResourceManager.GetString("MsgNewFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not a follower..
        /// </summary>
        internal static string MsgNotFollower {
            get {
                return ResourceManager.GetString("MsgNotFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No usage available..
        /// </summary>
        internal static string MsgNoUsage {
            get {
                return ResourceManager.GetString("MsgNoUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use -!join &apos;gamertag&apos;- to join the queue, and !leave to leave the queue..
        /// </summary>
        internal static string Msgqinfo {
            get {
                return ResourceManager.GetString("Msgqinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The queue list to join me in the game has started!.
        /// </summary>
        internal static string Msgqstart {
            get {
                return ResourceManager.GetString("Msgqstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The queue list to join me has stopped..
        /// </summary>
        internal static string Msgqstop {
            get {
                return ResourceManager.GetString("Msgqstop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message isn&apos;t used in response..
        /// </summary>
        internal static string Msgqueue {
            get {
                return ResourceManager.GetString("Msgqueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for bringing #viewers and raiding the channel!.
        /// </summary>
        internal static string MsgRaid {
            get {
                return ResourceManager.GetString("MsgRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for re-subscribing!.
        /// </summary>
        internal static string MsgResubscribe {
            get {
                return ResourceManager.GetString("MsgResubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for returning to the channel!.
        /// </summary>
        internal static string MsgReturnUserJoined {
            get {
                return ResourceManager.GetString("MsgReturnUserJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go check a great streamer #user, at #url!.
        /// </summary>
        internal static string Msgso {
            get {
                return ResourceManager.GetString("Msgso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are all of my social media connections: .
        /// </summary>
        internal static string Msgsocials {
            get {
                return ResourceManager.GetString("Msgsocials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream is offline..
        /// </summary>
        internal static string Msgstreamoffline {
            get {
                return ResourceManager.GetString("Msgstreamoffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for the subscribing!.
        /// </summary>
        internal static string MsgSubscribe {
            get {
                return ResourceManager.GetString("MsgSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for supporting the channel and welcome back to stream!.
        /// </summary>
        internal static string MsgSupporterJoined {
            get {
                return ResourceManager.GetString("MsgSupporterJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #user has returned. Welcome back!.
        /// </summary>
        internal static string Msgunlurk {
            get {
                return ResourceManager.GetString("Msgunlurk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #user has been streaming for #uptime..
        /// </summary>
        internal static string Msguptime {
            get {
                return ResourceManager.GetString("Msguptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for stopping by the channel!.
        /// </summary>
        internal static string MsgUserJoined {
            get {
                return ResourceManager.GetString("MsgUserJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #user has watched a total of #query..
        /// </summary>
        internal static string Msgwatchtime {
            get {
                return ResourceManager.GetString("Msgwatchtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #user is lurking while making some moohla! See you soon!.
        /// </summary>
        internal static string Msgworklurk {
            get {
                return ResourceManager.GetString("Msgworklurk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bit, bits.
        /// </summary>
        internal static string Pluralbits {
            get {
                return ResourceManager.GetString("Pluralbits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month, months.
        /// </summary>
        internal static string Pluralmonths {
            get {
                return ResourceManager.GetString("Pluralmonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscription, subscriptions.
        /// </summary>
        internal static string Pluralsub {
            get {
                return ResourceManager.GetString("Pluralsub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viewer, viewers.
        /// </summary>
        internal static string Pluralviewers {
            get {
                return ResourceManager.GetString("Pluralviewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qinfo.
        /// </summary>
        internal static string qinfo {
            get {
                return ResourceManager.GetString("qinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qstart.
        /// </summary>
        internal static string qstart {
            get {
                return ResourceManager.GetString("qstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qstop.
        /// </summary>
        internal static string qstop {
            get {
                return ResourceManager.GetString("qstop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to queue.
        /// </summary>
        internal static string queue {
            get {
                return ResourceManager.GetString("queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently not used..
        /// </summary>
        internal static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently not used..
        /// </summary>
        internal static string Respond {
            get {
                return ResourceManager.GetString("Respond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to so.
        /// </summary>
        internal static string so {
            get {
                return ResourceManager.GetString("so", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to socials.
        /// </summary>
        internal static string socials {
            get {
                return ResourceManager.GetString("socials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twine Chatbot by WrithemTwine, #url#author, version {0}.{1}.{2}.{3} is now connected!.
        /// </summary>
        internal static string TwineBotInfo {
            get {
                return ResourceManager.GetString("TwineBotInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlurk.
        /// </summary>
        internal static string unlurk {
            get {
                return ResourceManager.GetString("unlurk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uptime.
        /// </summary>
        internal static string uptime {
            get {
                return ResourceManager.GetString("uptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to watchtime.
        /// </summary>
        internal static string watchtime {
            get {
                return ResourceManager.GetString("watchtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to worklurk.
        /// </summary>
        internal static string worklurk {
            get {
                return ResourceManager.GetString("worklurk", resourceCulture);
            }
        }
    }
}
