//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamerBotLib.Culture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Msgs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Msgs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StreamerBotLib.Culture.Msgs", typeof(Msgs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accountage.
        /// </summary>
        internal static string accountage {
            get {
                return ResourceManager.GetString("accountage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addcommand.
        /// </summary>
        internal static string addcommand {
            get {
                return ResourceManager.GetString("addcommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approve.
        /// </summary>
        internal static string approve {
            get {
                return ResourceManager.GetString("approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto-hosting.
        /// </summary>
        internal static string autohost {
            get {
                return ResourceManager.GetString("autohost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blackjack.
        /// </summary>
        internal static string blackjack {
            get {
                return ResourceManager.GetString("blackjack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You made BlackJack 21!.
        /// </summary>
        internal static string BlackJack21Win {
            get {
                return ResourceManager.GetString("BlackJack21Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, you went over 21!.
        /// </summary>
        internal static string BlackJackBust {
            get {
                return ResourceManager.GetString("BlackJackBust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you have #cards, totaling #value..
        /// </summary>
        internal static string BlackJackCardMessage {
            get {
                return ResourceManager.GetString("BlackJackCardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You and the House both have the same points, ending in a draw..
        /// </summary>
        internal static string BlackJackDraw {
            get {
                return ResourceManager.GetString("BlackJackDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to #hit (another card) or #stand (no card)?.
        /// </summary>
        internal static string BlackJackHit {
            get {
                return ResourceManager.GetString("BlackJackHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The House busts over 21..
        /// </summary>
        internal static string BlackJackHouseBusts {
            get {
                return ResourceManager.GetString("BlackJackHouseBusts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The House has #cards, totaling #value..
        /// </summary>
        internal static string BlackJackHouseCardMsg {
            get {
                return ResourceManager.GetString("BlackJackHouseCardMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The House has 21..
        /// </summary>
        internal static string BlackJackHouseHits21 {
            get {
                return ResourceManager.GetString("BlackJackHouseHits21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The House stands..
        /// </summary>
        internal static string BlackJackHouseStands {
            get {
                return ResourceManager.GetString("BlackJackHouseStands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The house wins..
        /// </summary>
        internal static string BlackJackHouseWin {
            get {
                return ResourceManager.GetString("BlackJackHouseWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency is not setup in Built-In Command !blackJack, &apos;currencyfield&apos; value..
        /// </summary>
        internal static string BlackJackNoCurrency {
            get {
                return ResourceManager.GetString("BlackJackNoCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlackJack no longer accepting new players. Try next round..
        /// </summary>
        internal static string BlackJackNoJoin {
            get {
                return ResourceManager.GetString("BlackJackNoJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player not registered..
        /// </summary>
        internal static string BlackJackNoPlayer {
            get {
                return ResourceManager.GetString("BlackJackNoPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payout is #payout..
        /// </summary>
        internal static string BlackJackPayout {
            get {
                return ResourceManager.GetString("BlackJackPayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #user is sitting at the BlackJack table..
        /// </summary>
        internal static string BlackJackPlayerJoined {
            get {
                return ResourceManager.GetString("BlackJackPlayerJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #user does not have enough currency to play..
        /// </summary>
        internal static string BlackJackPlayerNoMoney {
            get {
                return ResourceManager.GetString("BlackJackPlayerNoMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now dealing to each player.  When it&apos;s your turn, you have 30 seconds to type words or phrases containing &apos;#hit&apos; or &apos;#stand&apos;-(normal viewers can be prevented from typing the same phrase in a short time).
        /// </summary>
        internal static string BlackJackStart {
            get {
                return ResourceManager.GetString("BlackJackStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You beat the house!.
        /// </summary>
        internal static string BlackJackWinOverHouse {
            get {
                return ResourceManager.GetString("BlackJackWinOverHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bot.
        /// </summary>
        internal static string bot {
            get {
                return ResourceManager.GetString("bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancelraid.
        /// </summary>
        internal static string cancelraid {
            get {
                return ResourceManager.GetString("cancelraid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commands.
        /// </summary>
        internal static string commands {
            get {
                return ResourceManager.GetString("commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dead.
        /// </summary>
        internal static string dead {
            get {
                return ResourceManager.GetString("dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dequeue.
        /// </summary>
        internal static string dequeue {
            get {
                return ResourceManager.GetString("dequeue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to editcommand.
        /// </summary>
        internal static string editcommand {
            get {
                return ResourceManager.GetString("editcommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enqueue.
        /// </summary>
        internal static string enqueue {
            get {
                return ResourceManager.GetString("enqueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @everyone.
        /// </summary>
        internal static string everyone {
            get {
                return ResourceManager.GetString("everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied value {0} is not included within the acceptable list: {1}.
        /// </summary>
        internal static string ExceptionArgument {
            get {
                return ResourceManager.GetString("ExceptionArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permission to invoke this command..
        /// </summary>
        internal static string ExceptionInvalidCommand {
            get {
                return ResourceManager.GetString("ExceptionInvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command {0} is configured for {1}, but can only perform {2}.
        /// </summary>
        internal static string ExceptionInvalidComUsage {
            get {
                return ResourceManager.GetString("ExceptionInvalidComUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not found..
        /// </summary>
        internal static string ExceptionInvalidOpCommand {
            get {
                return ResourceManager.GetString("ExceptionInvalidOpCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field not specified..
        /// </summary>
        internal static string ExceptionInvalidOperationField {
            get {
                return ResourceManager.GetString("ExceptionInvalidOperationField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table not specified..
        /// </summary>
        internal static string ExceptionInvalidOperationTable {
            get {
                return ResourceManager.GetString("ExceptionInvalidOperationTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not found..
        /// </summary>
        internal static string ExceptionKeyNotFound {
            get {
                return ResourceManager.GetString("ExceptionKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to followage.
        /// </summary>
        internal static string followage {
            get {
                return ResourceManager.GetString("followage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to permits distinguishing if the channel is hosted or autohosted.
        /// </summary>
        internal static string Helpautohost {
            get {
                return ResourceManager.GetString("Helpautohost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message to give when a user is banned..
        /// </summary>
        internal static string HelpBannedUser {
            get {
                return ResourceManager.GetString("HelpBannedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message displayed when a user hosts the channel. Currently only supported when the bot&apos;s user name is the same as the streamer&apos;s user name..
        /// </summary>
        internal static string HelpBeingHosted {
            get {
                return ResourceManager.GetString("HelpBeingHosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The thank you message when a user donates bits to the channel..
        /// </summary>
        internal static string Helpbits {
            get {
                return ResourceManager.GetString("Helpbits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackjack message showing current cards.
        /// </summary>
        internal static string Helpcards {
            get {
                return ResourceManager.GetString("Helpcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current category, can be used for current channel or referencing a viewer (as command parameter).
        /// </summary>
        internal static string Helpcategory {
            get {
                return ResourceManager.GetString("Helpcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter command used within the &apos;usage&apos; command.
        /// </summary>
        internal static string Helpcom {
            get {
                return ResourceManager.GetString("Helpcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you message for someone gifting subscription(s) to the channel.
        /// </summary>
        internal static string HelpCommunitySubs {
            get {
                return ResourceManager.GetString("HelpCommunitySubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the number of donated subscriptions with tier plan: e.g. 5 Tier 1 Subscriptions.
        /// </summary>
        internal static string Helpcount {
            get {
                return ResourceManager.GetString("Helpcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the current date in your timezone.
        /// </summary>
        internal static string Helpdate {
            get {
                return ResourceManager.GetString("Helpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies to uptime, displays the change in viewers since last query of live viewers..
        /// </summary>
        internal static string Helpdeltaviewers {
            get {
                return ResourceManager.GetString("Helpdeltaviewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When included, will replace &apos;#everyone&apos; with either (true) &apos;@everyone&apos; or (false) &apos;&lt;blank&gt;&apos; depending on whether the &apos;AddEveryone&apos; is checked (true) or unchecked (false) alongside the Discord Server link..
        /// </summary>
        internal static string Helpeveryone {
            get {
                return ResourceManager.GetString("Helpeveryone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome message for new follower to the channel.
        /// </summary>
        internal static string HelpFollow {
            get {
                return ResourceManager.GetString("HelpFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you message for someone gifting subscription(s) to a user.
        /// </summary>
        internal static string HelpGiftSub {
            get {
                return ResourceManager.GetString("HelpGiftSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackjack message name for &quot;hit&quot; asking for another card.
        /// </summary>
        internal static string Helphit {
            get {
                return ResourceManager.GetString("Helphit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackjack message about what value the House stands (takes no more cards).
        /// </summary>
        internal static string Helphousestand {
            get {
                return ResourceManager.GetString("Helphousestand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently not used..
        /// </summary>
        internal static string HelpJoinChannel {
            get {
                return ResourceManager.GetString("HelpJoinChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently not used..
        /// </summary>
        internal static string HelpLeaveChannel {
            get {
                return ResourceManager.GetString("HelpLeaveChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific to the moderator approval command, the list of pending approval items..
        /// </summary>
        internal static string Helplist {
            get {
                return ResourceManager.GetString("Helplist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message to send out to social media when the channel goes live..
        /// </summary>
        internal static string HelpLive {
            get {
                return ResourceManager.GetString("HelpLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how many months subscribed this time.
        /// </summary>
        internal static string Helpmonths {
            get {
                return ResourceManager.GetString("Helpmonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackjack message to show how much currency the player won.
        /// </summary>
        internal static string Helppayout {
            get {
                return ResourceManager.GetString("Helppayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The results of the command query will go here..
        /// </summary>
        internal static string Helpquery {
            get {
                return ResourceManager.GetString("Helpquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The welcome and thank you message when a user raids the channel.
        /// </summary>
        internal static string HelpRaid {
            get {
                return ResourceManager.GetString("HelpRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently not used..
        /// </summary>
        internal static string HelpRandom {
            get {
                return ResourceManager.GetString("HelpRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the user who received the gifted subscription.
        /// </summary>
        internal static string Helpreceiveuser {
            get {
                return ResourceManager.GetString("Helpreceiveuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently not used..
        /// </summary>
        internal static string HelpRespond {
            get {
                return ResourceManager.GetString("HelpRespond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The thank you message when a user resubscribes to the channel..
        /// </summary>
        internal static string HelpResubscribe {
            get {
                return ResourceManager.GetString("HelpResubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message to provide when a user/viewer is returning to the stream..
        /// </summary>
        internal static string HelpReturnUserJoined {
            get {
                return ResourceManager.GetString("HelpReturnUserJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackjack message name for &quot;stand&quot; to not take another card.
        /// </summary>
        internal static string Helpstand {
            get {
                return ResourceManager.GetString("Helpstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current sub streak months, depends on user preference to share.
        /// </summary>
        internal static string Helpstreak {
            get {
                return ResourceManager.GetString("Helpstreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how many overall months subscribed.
        /// </summary>
        internal static string Helpsubmonths {
            get {
                return ResourceManager.GetString("Helpsubmonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the subscription plan.
        /// </summary>
        internal static string Helpsubplan {
            get {
                return ResourceManager.GetString("Helpsubplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the subscription plan name.
        /// </summary>
        internal static string Helpsubplanname {
            get {
                return ResourceManager.GetString("Helpsubplanname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The thank you message when a user subscribes to the channel..
        /// </summary>
        internal static string HelpSubscribe {
            get {
                return ResourceManager.GetString("HelpSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message to provide when user/viewer is a follower to the stream and supporting the channel..
        /// </summary>
        internal static string HelpSupporterJoined {
            get {
                return ResourceManager.GetString("HelpSupporterJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the current time in your timezone.
        /// </summary>
        internal static string Helptime {
            get {
                return ResourceManager.GetString("Helptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current live stream title.
        /// </summary>
        internal static string Helptitle {
            get {
                return ResourceManager.GetString("Helptitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specific detailed message the bot chats upon joining the channel..
        /// </summary>
        internal static string HelpTwineBotInfo {
            get {
                return ResourceManager.GetString("HelpTwineBotInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify user&apos;s name, will add Twitch&apos;s URL prefix.
        /// </summary>
        internal static string Helpurl {
            get {
                return ResourceManager.GetString("Helpurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows the message usage.
        /// </summary>
        internal static string Helpusage {
            get {
                return ResourceManager.GetString("Helpusage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display name of the user sending action, some contexts - the streamer.
        /// </summary>
        internal static string Helpuser {
            get {
                return ResourceManager.GetString("Helpuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message the bot uses to welcome users to the channel. See options for &quot;no welcome&quot;, &quot;welcome when joined&quot;, or &quot;welcome when user chats&quot;..
        /// </summary>
        internal static string HelpUserJoined {
            get {
                return ResourceManager.GetString("HelpUserJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackjack message for card value **or** a general number value in some contexts.
        /// </summary>
        internal static string Helpvalue {
            get {
                return ResourceManager.GetString("Helpvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display the number of viewers.
        /// </summary>
        internal static string Helpviewers {
            get {
                return ResourceManager.GetString("Helpviewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display winner of Giveaway event.
        /// </summary>
        internal static string Helpwinner {
            get {
                return ResourceManager.GetString("Helpwinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hit.
        /// </summary>
        internal static string hit {
            get {
                return ResourceManager.GetString("hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hosting.
        /// </summary>
        internal static string host {
            get {
                return ResourceManager.GetString("host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intro.
        /// </summary>
        internal static string intro {
            get {
                return ResourceManager.GetString("intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to join.
        /// </summary>
        internal static string join {
            get {
                return ResourceManager.GetString("join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently not used..
        /// </summary>
        internal static string JoinChannel {
            get {
                return ResourceManager.GetString("JoinChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leave.
        /// </summary>
        internal static string leave {
            get {
                return ResourceManager.GetString("leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently not used..
        /// </summary>
        internal static string LeaveChannel {
            get {
                return ResourceManager.GetString("LeaveChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lurk.
        /// </summary>
        internal static string lurk {
            get {
                return ResourceManager.GetString("lurk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mergeaccounts.
        /// </summary>
        internal static string mergeaccounts {
            get {
                return ResourceManager.GetString("mergeaccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account #user created #date ago..
        /// </summary>
        internal static string Msgaccountage {
            get {
                return ResourceManager.GetString("Msgaccountage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command {0} added!.
        /// </summary>
        internal static string Msgaddcommand {
            get {
                return ResourceManager.GetString("Msgaddcommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string MsgAllCateogry {
            get {
                return ResourceManager.GetString("MsgAllCateogry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A moderator needs to approve (#usage): #list.
        /// </summary>
        internal static string Msgapprove {
            get {
                return ResourceManager.GetString("Msgapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #user was just banned..
        /// </summary>
        internal static string MsgBannedUser {
            get {
                return ResourceManager.GetString("MsgBannedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for #autohost this channel!.
        /// </summary>
        internal static string MsgBeingHosted {
            get {
                return ResourceManager.GetString("MsgBeingHosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for giving #bits!.
        /// </summary>
        internal static string MsgBits {
            get {
                return ResourceManager.GetString("MsgBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #user started a game of BlackJack-21! For the next 1 minute, use &quot;!blackjack &lt;amount&gt;&quot; to join and wager virtual stream currency! The objective is to reach 21 without going over (bust). The 2-10 cards are face value, Q J K are worth 10, and A are worth 1 or 11. The House stands at #housestand or higher. All ties are a draw, players receive their wager. Each player gets a turn to &apos;#hit&apos; for a card, or &apos;#stand&apos;. No answer means a &apos;#stand&apos;. Payouts at the end of the game..
        /// </summary>
        internal static string Msgblackjack {
            get {
                return ResourceManager.GetString("Msgblackjack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twine Streamer Bot written by WrithemTwine, https://github.com/WrithemTwine/TwineChatBot/ . Free to try and use, just give attribution. Testers needed..
        /// </summary>
        internal static string Msgbot {
            get {
                return ResourceManager.GetString("Msgbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $&quot;Fatal error, both main data and backup data files failed to properly load. All further data saves have been suspended until the Bot restarts. Please close and review the data files for improper XML formatting, retore from backups - ensure using the &apos;{StreamerBotLib.Data.DataManager.DataFileXML}&apos; filename. Without restoration, the datafile will need to be restarted from default.&quot;.
        /// </summary>
        internal static string MsgBoxDataLoadedMsg {
            get {
                return ResourceManager.GetString("MsgBoxDataLoadedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal DataFile Load.
        /// </summary>
        internal static string MsgBoxDataLoadedTitle {
            get {
                return ResourceManager.GetString("MsgBoxDataLoadedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is responsible for managing the datafile archives. The bot saves a backup file every approximate 15 minutes during a live stream. The bot attempts to load the original datafile first, then if there&apos;s an error, will attempt to load the backup file. With user requests, the bot could be programmed to save a timestamp named backup file to aid in this archive process. Possible future features include allowing the user to specify a SQL Database connection string, therefore archiving and backups could the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgBoxManageDataArchiveMsg {
            get {
                return ResourceManager.GetString("MsgBoxManageDataArchiveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Shows Once and When Setting Is Reset to Default.
        /// </summary>
        internal static string MsgBoxManageDataArchiveTitle {
            get {
                return ResourceManager.GetString("MsgBoxManageDataArchiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not found..
        /// </summary>
        internal static string Msgcommandnotfound {
            get {
                return ResourceManager.GetString("Msgcommandnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of commands: #query.
        /// </summary>
        internal static string Msgcommands {
            get {
                return ResourceManager.GetString("Msgcommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for giving #count to the community!.
        /// </summary>
        internal static string MsgCommunitySubs {
            get {
                return ResourceManager.GetString("MsgCommunitySubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data not found..
        /// </summary>
        internal static string MsgDataNotFound {
            get {
                return ResourceManager.GetString("MsgDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #user has now died #value while playing #category..
        /// </summary>
        internal static string Msgdead {
            get {
                return ResourceManager.GetString("Msgdead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default command, not changed..
        /// </summary>
        internal static string Msgdefaultcommand {
            get {
                return ResourceManager.GetString("Msgdefaultcommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also with leave, user leaves the play list.
        /// </summary>
        internal static string Msgdequeue {
            get {
                return ResourceManager.GetString("Msgdequeue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command {0} edited!.
        /// </summary>
        internal static string Msgeditcommand {
            get {
                return ResourceManager.GetString("Msgeditcommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also with join, user join the play list.
        /// </summary>
        internal static string Msgenqueue {
            get {
                return ResourceManager.GetString("Msgenqueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are enjoying the content, please hit that follow button!.
        /// </summary>
        internal static string Msgfollow {
            get {
                return ResourceManager.GetString("Msgfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #user has followed for #query!.
        /// </summary>
        internal static string Msgfollowage {
            get {
                return ResourceManager.GetString("Msgfollowage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for gifting a #subplan subscription to #receiveuser!.
        /// </summary>
        internal static string MsgGiftSub {
            get {
                return ResourceManager.GetString("MsgGiftSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #query.
        /// </summary>
        internal static string Msgintro {
            get {
                return ResourceManager.GetString("Msgintro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message isn&apos;t used in response..
        /// </summary>
        internal static string Msgjoin {
            get {
                return ResourceManager.GetString("Msgjoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message isn&apos;t used in response..
        /// </summary>
        internal static string Msgleave {
            get {
                return ResourceManager.GetString("Msgleave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #everyone #user is now live streaming #category - #title! Come join and say hi at: #url.
        /// </summary>
        internal static string MsgLive {
            get {
                return ResourceManager.GetString("MsgLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #user is now lurking. See you soon!.
        /// </summary>
        internal static string Msglurk {
            get {
                return ResourceManager.GetString("Msglurk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account merge failed..
        /// </summary>
        internal static string MsgMergeFailed {
            get {
                return ResourceManager.GetString("MsgMergeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts successfully merged..
        /// </summary>
        internal static string MsgMergeSuccessful {
            get {
                return ResourceManager.GetString("MsgMergeSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator approval accepted..
        /// </summary>
        internal static string MsgModApproved {
            get {
                return ResourceManager.GetString("MsgModApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval item not found..
        /// </summary>
        internal static string MsgModApproveNotFound {
            get {
                return ResourceManager.GetString("MsgModApproveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for the follow!.
        /// </summary>
        internal static string MsgNewFollow {
            get {
                return ResourceManager.GetString("MsgNewFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Category.
        /// </summary>
        internal static string MsgNoCategory {
            get {
                return ResourceManager.GetString("MsgNoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command did not perform successfully..
        /// </summary>
        internal static string MsgNoSuccess {
            get {
                return ResourceManager.GetString("MsgNoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not a follower..
        /// </summary>
        internal static string MsgNotFollower {
            get {
                return ResourceManager.GetString("MsgNotFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a title or category to update..
        /// </summary>
        internal static string MsgNoTitleCategory {
            get {
                return ResourceManager.GetString("MsgNoTitleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No usage available..
        /// </summary>
        internal static string MsgNoUsage {
            get {
                return ResourceManager.GetString("MsgNoUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        internal static string MsgNoUserFound {
            get {
                return ResourceManager.GetString("MsgNoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use -!join &apos;gamertag&apos;- (or !enqueue) to join the queue, and !leave (or !dequeue) to leave the queue..
        /// </summary>
        internal static string Msgqinfo {
            get {
                return ResourceManager.GetString("Msgqinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The queue list to join me in the game has started!.
        /// </summary>
        internal static string Msgqstart {
            get {
                return ResourceManager.GetString("Msgqstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The queue list to join me is stopped..
        /// </summary>
        internal static string Msgqstop {
            get {
                return ResourceManager.GetString("Msgqstop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The details of the queue, list who is in it.
        /// </summary>
        internal static string Msgqueue {
            get {
                return ResourceManager.GetString("Msgqueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for bringing #viewers and raiding the channel!.
        /// </summary>
        internal static string MsgRaid {
            get {
                return ResourceManager.GetString("MsgRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command removed.
        /// </summary>
        internal static string Msgremovecommand {
            get {
                return ResourceManager.GetString("Msgremovecommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game #category death counter reset to #value..
        /// </summary>
        internal static string Msgresetdead {
            get {
                return ResourceManager.GetString("Msgresetdead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for re-subscribing!.
        /// </summary>
        internal static string MsgResubscribe {
            get {
                return ResourceManager.GetString("MsgResubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for returning to the channel!.
        /// </summary>
        internal static string MsgReturnUserJoined {
            get {
                return ResourceManager.GetString("MsgReturnUserJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream category is now updated..
        /// </summary>
        internal static string Msgsetcategory {
            get {
                return ResourceManager.GetString("Msgsetcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream title is now updated..
        /// </summary>
        internal static string Msgsettitle {
            get {
                return ResourceManager.GetString("Msgsettitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go check out #user at #url and consider following them! They were last streaming: #category.
        /// </summary>
        internal static string Msgso {
            get {
                return ResourceManager.GetString("Msgso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message isn&apos;t used in response..
        /// </summary>
        internal static string Msgsoactive {
            get {
                return ResourceManager.GetString("Msgsoactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are my social media connections: .
        /// </summary>
        internal static string Msgsocials {
            get {
                return ResourceManager.GetString("Msgsocials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream is offline..
        /// </summary>
        internal static string Msgstreamoffline {
            get {
                return ResourceManager.GetString("Msgstreamoffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for the subscribing!.
        /// </summary>
        internal static string MsgSubscribe {
            get {
                return ResourceManager.GetString("MsgSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for supporting the channel and welcome back to stream!.
        /// </summary>
        internal static string MsgSupporterJoined {
            get {
                return ResourceManager.GetString("MsgSupporterJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #user has returned. Welcome back!.
        /// </summary>
        internal static string Msgunlurk {
            get {
                return ResourceManager.GetString("Msgunlurk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #user has been streaming for #uptime, with #viewers (#deltaviewers)..
        /// </summary>
        internal static string Msguptime {
            get {
                return ResourceManager.GetString("Msguptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The #com usage is: #query.
        /// </summary>
        internal static string Msgusage {
            get {
                return ResourceManager.GetString("Msgusage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks #user for stopping by the channel!.
        /// </summary>
        internal static string MsgUserJoined {
            get {
                return ResourceManager.GetString("MsgUserJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #user has watched a total of #query..
        /// </summary>
        internal static string Msgwatchtime {
            get {
                return ResourceManager.GetString("Msgwatchtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #user is lurking while making some moohla! See you soon!.
        /// </summary>
        internal static string Msgworklurk {
            get {
                return ResourceManager.GetString("Msgworklurk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} or {1}.
        /// </summary>
        internal static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -param:true -use:!accountage or !accountage &lt;viewername&gt;.
        /// </summary>
        internal static string Paramaccountage {
            get {
                return ResourceManager.GetString("Paramaccountage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p:Mod -param:true -use:!addcommand command &lt;switches-optional&gt; &lt;message&gt;. See documentation for &lt;switches&gt;..
        /// </summary>
        internal static string Paramaddcommand {
            get {
                return ResourceManager.GetString("Paramaddcommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p:Mod -use:!approve &lt;item number&gt;.
        /// </summary>
        internal static string Paramapprove {
            get {
                return ResourceManager.GetString("Paramapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -param:true -t:Currency -use:!blackjack &lt;wager&gt; (number), to start or enter the game!.
        /// </summary>
        internal static string Paramblackjack {
            get {
                return ResourceManager.GetString("Paramblackjack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -use:!bot.
        /// </summary>
        internal static string Parambot {
            get {
                return ResourceManager.GetString("Parambot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -use:!cancelraid Mod only -p:Mod.
        /// </summary>
        internal static string Paramcancelraid {
            get {
                return ResourceManager.GetString("Paramcancelraid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -t:Commands -f:CmdName -top:-1 -s:ASC -use:!commands.
        /// </summary>
        internal static string Paramcommands {
            get {
                return ResourceManager.GetString("Paramcommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -use:!dead {uses current category}.
        /// </summary>
        internal static string Paramdead {
            get {
                return ResourceManager.GetString("Paramdead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -use:!dequeue.
        /// </summary>
        internal static string Paramdequeue {
            get {
                return ResourceManager.GetString("Paramdequeue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -use:!&lt;social_name&gt;.
        /// </summary>
        internal static string Parameachsocial {
            get {
                return ResourceManager.GetString("Parameachsocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p:Mod -param:true -use:!editcommand command &lt;switches-optional&gt; &lt;message&gt;. See documentation for &lt;switches&gt;..
        /// </summary>
        internal static string Parameditcommand {
            get {
                return ResourceManager.GetString("Parameditcommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -use:!enqueue.
        /// </summary>
        internal static string Paramenqueue {
            get {
                return ResourceManager.GetString("Paramenqueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -use:!follow.
        /// </summary>
        internal static string Paramfollow {
            get {
                return ResourceManager.GetString("Paramfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -t:Followers -f:FollowedDate -param:true -use:!followage or !followage &lt;user&gt;.
        /// </summary>
        internal static string Paramfollowage {
            get {
                return ResourceManager.GetString("Paramfollowage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -t:CustomWelcome -param:true -f:Message -use:!intro username.
        /// </summary>
        internal static string Paramintro {
            get {
                return ResourceManager.GetString("Paramintro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -use:!join.
        /// </summary>
        internal static string Paramjoin {
            get {
                return ResourceManager.GetString("Paramjoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -use:!leave.
        /// </summary>
        internal static string Paramleave {
            get {
                return ResourceManager.GetString("Paramleave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -use:!lurk.
        /// </summary>
        internal static string Paramlurk {
            get {
                return ResourceManager.GetString("Paramlurk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p:Mod -use:(Mod level) !mergeaccounts &lt;currname&gt; &lt;previousname&gt; &apos;or&apos; (user level) !mergeaccounts &lt;previousname&gt;.
        /// </summary>
        internal static string Parammergeaccounts {
            get {
                return ResourceManager.GetString("Parammergeaccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -use:!qinfo.
        /// </summary>
        internal static string Paramqinfo {
            get {
                return ResourceManager.GetString("Paramqinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p:Mod -use:!qstart mod only.
        /// </summary>
        internal static string Paramqstart {
            get {
                return ResourceManager.GetString("Paramqstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p:Mod -use:!qstop mod only.
        /// </summary>
        internal static string Paramqstop {
            get {
                return ResourceManager.GetString("Paramqstop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p:Mod -use:!queue mods only.
        /// </summary>
        internal static string Paramqueue {
            get {
                return ResourceManager.GetString("Paramqueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -use:!raid &lt;user&gt; Mod only -param:true -p:Mod.
        /// </summary>
        internal static string Paramraid {
            get {
                return ResourceManager.GetString("Paramraid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p:Mod -param:true -use:!removecommand command. Does not remove default commands..
        /// </summary>
        internal static string Paramremovecommand {
            get {
                return ResourceManager.GetString("Paramremovecommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p:Mod -param:true -use:!resetdead &lt;number&gt; {uses current category, reset to 0 or &lt;number&gt;}.
        /// </summary>
        internal static string Paramresetdead {
            get {
                return ResourceManager.GetString("Paramresetdead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -use:!setcategory -p:Mod -param:true.
        /// </summary>
        internal static string Paramsetcategory {
            get {
                return ResourceManager.GetString("Paramsetcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -t:CustomWelcome -param:true -p:Mod -f:Message -a:Post -use:!intro username message.
        /// </summary>
        internal static string Paramsetintro {
            get {
                return ResourceManager.GetString("Paramsetintro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -use:!settitle -p:Mod -param:true.
        /// </summary>
        internal static string Paramsettitle {
            get {
                return ResourceManager.GetString("Paramsettitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p:Mod -param:true -use:!so username - only mods can use !so..
        /// </summary>
        internal static string Paramso {
            get {
                return ResourceManager.GetString("Paramso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -use:!soactive -p:Mod.
        /// </summary>
        internal static string Paramsoactive {
            get {
                return ResourceManager.GetString("Paramsoactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -use:!socials.
        /// </summary>
        internal static string Paramsocials {
            get {
                return ResourceManager.GetString("Paramsocials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -use:!unlurk.
        /// </summary>
        internal static string Paramunlurk {
            get {
                return ResourceManager.GetString("Paramunlurk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -use:!uptime -param:true.
        /// </summary>
        internal static string Paramuptime {
            get {
                return ResourceManager.GetString("Paramuptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -t:Commands -f:Usage -param:true -use:!usage &lt;command&gt;.
        /// </summary>
        internal static string Paramusage {
            get {
                return ResourceManager.GetString("Paramusage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -t:Users -f:WatchTime -param:true -use:!watchtime or !watchtime &lt;user&gt;.
        /// </summary>
        internal static string Paramwatchtime {
            get {
                return ResourceManager.GetString("Paramwatchtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -use:!worklurk.
        /// </summary>
        internal static string Paramworklurk {
            get {
                return ResourceManager.GetString("Paramworklurk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payout.
        /// </summary>
        internal static string payout {
            get {
                return ResourceManager.GetString("payout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bit, bits.
        /// </summary>
        internal static string Pluralbits {
            get {
                return ResourceManager.GetString("Pluralbits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day, days.
        /// </summary>
        internal static string Pluralday {
            get {
                return ResourceManager.GetString("Pluralday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour, hours.
        /// </summary>
        internal static string Pluralhour {
            get {
                return ResourceManager.GetString("Pluralhour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute, minutes.
        /// </summary>
        internal static string Pluralminute {
            get {
                return ResourceManager.GetString("Pluralminute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month, months.
        /// </summary>
        internal static string Pluralmonth {
            get {
                return ResourceManager.GetString("Pluralmonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscription, subscriptions.
        /// </summary>
        internal static string Pluralsub {
            get {
                return ResourceManager.GetString("Pluralsub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time, times.
        /// </summary>
        internal static string Pluraltime {
            get {
                return ResourceManager.GetString("Pluraltime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viewer, viewers.
        /// </summary>
        internal static string Pluralviewers {
            get {
                return ResourceManager.GetString("Pluralviewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year, years.
        /// </summary>
        internal static string Pluralyear {
            get {
                return ResourceManager.GetString("Pluralyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qinfo.
        /// </summary>
        internal static string qinfo {
            get {
                return ResourceManager.GetString("qinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qstart.
        /// </summary>
        internal static string qstart {
            get {
                return ResourceManager.GetString("qstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qstop.
        /// </summary>
        internal static string qstop {
            get {
                return ResourceManager.GetString("qstop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to queue.
        /// </summary>
        internal static string queue {
            get {
                return ResourceManager.GetString("queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raid.
        /// </summary>
        internal static string raid {
            get {
                return ResourceManager.GetString("raid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently not used..
        /// </summary>
        internal static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removecommand.
        /// </summary>
        internal static string removecommand {
            get {
                return ResourceManager.GetString("removecommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resetdead.
        /// </summary>
        internal static string resetdead {
            get {
                return ResourceManager.GetString("resetdead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently not used..
        /// </summary>
        internal static string Respond {
            get {
                return ResourceManager.GetString("Respond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setcategory.
        /// </summary>
        internal static string setcategory {
            get {
                return ResourceManager.GetString("setcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setintro.
        /// </summary>
        internal static string setintro {
            get {
                return ResourceManager.GetString("setintro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settitle.
        /// </summary>
        internal static string settitle {
            get {
                return ResourceManager.GetString("settitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to so.
        /// </summary>
        internal static string so {
            get {
                return ResourceManager.GetString("so", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to soactive.
        /// </summary>
        internal static string soactive {
            get {
                return ResourceManager.GetString("soactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to socials.
        /// </summary>
        internal static string socials {
            get {
                return ResourceManager.GetString("socials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stand.
        /// </summary>
        internal static string stand {
            get {
                return ResourceManager.GetString("stand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to streamer.
        /// </summary>
        internal static string streamer {
            get {
                return ResourceManager.GetString("streamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twine Chat Bot by WrithemTwine, #url, version {0}.{1}.{2}.{3} is now connected!.
        /// </summary>
        internal static string TwineBotInfo {
            get {
                return ResourceManager.GetString("TwineBotInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlurk.
        /// </summary>
        internal static string unlurk {
            get {
                return ResourceManager.GetString("unlurk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uptime.
        /// </summary>
        internal static string uptime {
            get {
                return ResourceManager.GetString("uptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usage.
        /// </summary>
        internal static string usage {
            get {
                return ResourceManager.GetString("usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to watchtime.
        /// </summary>
        internal static string watchtime {
            get {
                return ResourceManager.GetString("watchtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to worklurk.
        /// </summary>
        internal static string worklurk {
            get {
                return ResourceManager.GetString("worklurk", resourceCulture);
            }
        }
    }
}
