//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamerBotLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StreamerBotLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WrithemTwine.
        /// </summary>
        public static string AuthorTwitch {
            get {
                return ResourceManager.GetString("AuthorTwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bits:read chat:read chat:edit channel:moderate moderator:manage:banned_users moderator:read:followers channel:read:redemptions channel:manage:broadcast channel:manage:raids.
        /// </summary>
        public static string CredentialsTwitchPriorFullScope {
            get {
                return ResourceManager.GetString("CredentialsTwitchPriorFullScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bits:read chat:read chat:edit channel:moderate moderator:manage:banned_users moderator:read:followers.
        /// </summary>
        public static string CredentialsTwitchScopesDiffOauthBot {
            get {
                return ResourceManager.GetString("CredentialsTwitchScopesDiffOauthBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to channel:read:redemptions channel:manage:broadcast channel:manage:raids.
        /// </summary>
        public static string CredentialsTwitchScopesDiffOauthChannel {
            get {
                return ResourceManager.GetString("CredentialsTwitchScopesDiffOauthChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bits:read chat:read chat:edit channel:moderate moderator:manage:banned_users moderator:read:followers channel:read:redemptions channel:manage:broadcast channel:manage:raids.
        /// </summary>
        public static string CredentialsTwitchScopesOauthSame {
            get {
                return ResourceManager.GetString("CredentialsTwitchScopesOauthSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/WrithemTwine/TwineChatBot/releases/.
        /// </summary>
        public static string GitHubLatestLink {
            get {
                return ResourceManager.GetString("GitHubLatestLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/WrithemTwine/TwineChatBot/releases/latest.
        /// </summary>
        public static string GitHubStableLink {
            get {
                return ResourceManager.GetString("GitHubStableLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/WrithemTwine/TwineChatBot/wiki.
        /// </summary>
        public static string GitHubWikiLink {
            get {
                return ResourceManager.GetString("GitHubWikiLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitch.tv/.
        /// </summary>
        public static string TwitchHomepage {
            get {
                return ResourceManager.GetString("TwitchHomepage", resourceCulture);
            }
        }
    }
}
