//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamerBotLib.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public decimal ChatPopOutOpacity {
            get {
                return ((decimal)(this["ChatPopOutOpacity"]));
            }
            set {
                this["ChatPopOutOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogBotStatus {
            get {
                return ((bool)(this["LogBotStatus"]));
            }
            set {
                this["LogBotStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogExceptions {
            get {
                return ((bool)(this["LogExceptions"]));
            }
            set {
                this["LogExceptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ManageFollowers {
            get {
                return ((bool)(this["ManageFollowers"]));
            }
            set {
                this["ManageFollowers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ManageRaidData {
            get {
                return ((bool)(this["ManageRaidData"]));
            }
            set {
                this["ManageRaidData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ManageStreamStats {
            get {
                return ((bool)(this["ManageStreamStats"]));
            }
            set {
                this["ManageStreamStats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ManageUsers {
            get {
                return ((bool)(this["ManageUsers"]));
            }
            set {
                this["ManageUsers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MsgAutoShout {
            get {
                return ((bool)(this["MsgAutoShout"]));
            }
            set {
                this["MsgAutoShout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MsgBotConnection {
            get {
                return ((bool)(this["MsgBotConnection"]));
            }
            set {
                this["MsgBotConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MsgInsertMe {
            get {
                return ((bool)(this["MsgInsertMe"]));
            }
            set {
                this["MsgInsertMe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#user is now live streaming #category - #title! Come join and say hi at: #url")]
        public string MsgLive {
            get {
                return ((string)(this["MsgLive"]));
            }
            set {
                this["MsgLive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MsgNoMe {
            get {
                return ((bool)(this["MsgNoMe"]));
            }
            set {
                this["MsgNoMe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MsgPerComMe {
            get {
                return ((bool)(this["MsgPerComMe"]));
            }
            set {
                this["MsgPerComMe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MsgWelcomeStreamer {
            get {
                return ((bool)(this["MsgWelcomeStreamer"]));
            }
            set {
                this["MsgWelcomeStreamer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PostMultiLive {
            get {
                return ((bool)(this["PostMultiLive"]));
            }
            set {
                this["PostMultiLive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RepeatTimerCommands {
            get {
                return ((bool)(this["RepeatTimerCommands"]));
            }
            set {
                this["RepeatTimerCommands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RepeatTimerComSlowdown {
            get {
                return ((bool)(this["RepeatTimerComSlowdown"]));
            }
            set {
                this["RepeatTimerComSlowdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RepeatWhenLive {
            get {
                return ((bool)(this["RepeatWhenLive"]));
            }
            set {
                this["RepeatWhenLive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Specify the OAuth access token for bot authentication")]
        public string TwitchAccessToken {
            get {
                return ((string)(this["TwitchAccessToken"]));
            }
            set {
                this["TwitchAccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchAddFollowerNotification {
            get {
                return ((bool)(this["TwitchAddFollowerNotification"]));
            }
            set {
                this["TwitchAddFollowerNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchAddFollowersStart {
            get {
                return ((bool)(this["TwitchAddFollowersStart"]));
            }
            set {
                this["TwitchAddFollowersStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Twitch account the bot will use to post")]
        public string TwitchBotUserName {
            get {
                return ((string)(this["TwitchBotUserName"]));
            }
            set {
                this["TwitchBotUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Twitch channel the bot will monitor")]
        public string TwitchChannelName {
            get {
                return ((string)(this["TwitchChannelName"]));
            }
            set {
                this["TwitchChannelName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchChatBotAutoStart {
            get {
                return ((bool)(this["TwitchChatBotAutoStart"]));
            }
            set {
                this["TwitchChatBotAutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchChatBotConnectOnline {
            get {
                return ((bool)(this["TwitchChatBotConnectOnline"]));
            }
            set {
                this["TwitchChatBotConnectOnline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchChatBotDisconnectOffline {
            get {
                return ((bool)(this["TwitchChatBotDisconnectOffline"]));
            }
            set {
                this["TwitchChatBotDisconnectOffline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("From registered chatbot at https://dev.twitch.tv/console")]
        public string TwitchClientID {
            get {
                return ((string)(this["TwitchClientID"]));
            }
            set {
                this["TwitchClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchClipAutoStart {
            get {
                return ((bool)(this["TwitchClipAutoStart"]));
            }
            set {
                this["TwitchClipAutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchClipPostChat {
            get {
                return ((bool)(this["TwitchClipPostChat"]));
            }
            set {
                this["TwitchClipPostChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchClipPostDiscord {
            get {
                return ((bool)(this["TwitchClipPostDiscord"]));
            }
            set {
                this["TwitchClipPostDiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CurrencyOnline {
            get {
                return ((bool)(this["CurrencyOnline"]));
            }
            set {
                this["CurrencyOnline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CurrencyStart {
            get {
                return ((bool)(this["CurrencyStart"]));
            }
            set {
                this["CurrencyStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchDisconnectBot {
            get {
                return ((bool)(this["TwitchDisconnectBot"]));
            }
            set {
                this["TwitchDisconnectBot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchFollowerSvcAutoStart {
            get {
                return ((bool)(this["TwitchFollowerSvcAutoStart"]));
            }
            set {
                this["TwitchFollowerSvcAutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double TwitchFrequencyClipTime {
            get {
                return ((double)(this["TwitchFrequencyClipTime"]));
            }
            set {
                this["TwitchFrequencyClipTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int TwitchFrequencyFollow {
            get {
                return ((int)(this["TwitchFrequencyFollow"]));
            }
            set {
                this["TwitchFrequencyFollow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int TwitchGoLiveFrequency {
            get {
                return ((int)(this["TwitchGoLiveFrequency"]));
            }
            set {
                this["TwitchGoLiveFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchLiveStreamSvcAutoStart {
            get {
                return ((bool)(this["TwitchLiveStreamSvcAutoStart"]));
            }
            set {
                this["TwitchLiveStreamSvcAutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchMultiLiveAutoStart {
            get {
                return ((bool)(this["TwitchMultiLiveAutoStart"]));
            }
            set {
                this["TwitchMultiLiveAutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchPruneNonFollowers {
            get {
                return ((bool)(this["TwitchPruneNonFollowers"]));
            }
            set {
                this["TwitchPruneNonFollowers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchRaidShoutOut {
            get {
                return ((bool)(this["TwitchRaidShoutOut"]));
            }
            set {
                this["TwitchRaidShoutOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1900-01-01")]
        public global::System.DateTime TwitchRefreshDate {
            get {
                return ((global::System.DateTime)(this["TwitchRefreshDate"]));
            }
            set {
                this["TwitchRefreshDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Optional, some sites provide this token to refresh an OAuth access token")]
        public string TwitchRefreshToken {
            get {
                return ((string)(this["TwitchRefreshToken"]));
            }
            set {
                this["TwitchRefreshToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserPartyStart {
            get {
                return ((bool)(this["UserPartyStart"]));
            }
            set {
                this["UserPartyStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UserPartyStop {
            get {
                return ((bool)(this["UserPartyStop"]));
            }
            set {
                this["UserPartyStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FirstUserChatMsg {
            get {
                return ((bool)(this["FirstUserChatMsg"]));
            }
            set {
                this["FirstUserChatMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WelcomeCustomMsg {
            get {
                return ((bool)(this["WelcomeCustomMsg"]));
            }
            set {
                this["WelcomeCustomMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WelcomeDisabled {
            get {
                return ((bool)(this["WelcomeDisabled"]));
            }
            set {
                this["WelcomeDisabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FirstUserJoinedMsg {
            get {
                return ((bool)(this["FirstUserJoinedMsg"]));
            }
            set {
                this["FirstUserJoinedMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExpanderCredentialsHelp {
            get {
                return ((bool)(this["ExpanderCredentialsHelp"]));
            }
            set {
                this["ExpanderCredentialsHelp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugLiveStream {
            get {
                return ((bool)(this["DebugLiveStream"]));
            }
            set {
                this["DebugLiveStream"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ManageOutRaidData {
            get {
                return ((bool)(this["ManageOutRaidData"]));
            }
            set {
                this["ManageOutRaidData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RepeatLiveReset {
            get {
                return ((bool)(this["RepeatLiveReset"]));
            }
            set {
                this["RepeatLiveReset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RepeatLiveResetShow {
            get {
                return ((bool)(this["RepeatLiveResetShow"]));
            }
            set {
                this["RepeatLiveResetShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ManageGiveawayUsers {
            get {
                return ((bool)(this["ManageGiveawayUsers"]));
            }
            set {
                this["ManageGiveawayUsers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int GiveawayCount {
            get {
                return ((int)(this["GiveawayCount"]));
            }
            set {
                this["GiveawayCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The Giveaway winner is: #winner!")]
        public string GiveawayWinMsg {
            get {
                return ((string)(this["GiveawayWinMsg"]));
            }
            set {
                this["GiveawayWinMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The message when beginning giveaway - blank is no chat message")]
        public string GiveawayBegMsg {
            get {
                return ((string)(this["GiveawayBegMsg"]));
            }
            set {
                this["GiveawayBegMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The message when ending giveaway - blank is no chat message")]
        public string GiveawayEndMsg {
            get {
                return ((string)(this["GiveawayEndMsg"]));
            }
            set {
                this["GiveawayEndMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GiveawayMultiUser {
            get {
                return ((bool)(this["GiveawayMultiUser"]));
            }
            set {
                this["GiveawayMultiUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TwitchPubSubChannelPoints {
            get {
                return ((bool)(this["TwitchPubSubChannelPoints"]));
            }
            set {
                this["TwitchPubSubChannelPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("From registered chatbot for Stream Channel at https://dev.twitch.tv/console")]
        public string TwitchStreamClientId {
            get {
                return ((string)(this["TwitchStreamClientId"]));
            }
            set {
                this["TwitchStreamClientId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Specify the OAuth access token for streamer channel bot authentication")]
        public string TwitchStreamOauthToken {
            get {
                return ((string)(this["TwitchStreamOauthToken"]));
            }
            set {
                this["TwitchStreamOauthToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1900-01-01")]
        public global::System.DateTime TwitchStreamerTokenDate {
            get {
                return ((global::System.DateTime)(this["TwitchStreamerTokenDate"]));
            }
            set {
                this["TwitchStreamerTokenDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int GiveawayMaxEntries {
            get {
                return ((int)(this["GiveawayMaxEntries"]));
            }
            set {
                this["GiveawayMaxEntries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ManageDataArchiveMsg {
            get {
                return ((bool)(this["ManageDataArchiveMsg"]));
            }
            set {
                this["ManageDataArchiveMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchFollowerAutoRefresh {
            get {
                return ((bool)(this["TwitchFollowerAutoRefresh"]));
            }
            set {
                this["TwitchFollowerAutoRefresh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int TwitchFollowerRefreshHrs {
            get {
                return ((int)(this["TwitchFollowerRefreshHrs"]));
            }
            set {
                this["TwitchFollowerRefreshHrs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ModerateUsersWarn {
            get {
                return ((bool)(this["ModerateUsersWarn"]));
            }
            set {
                this["ModerateUsersWarn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ModerateUsersAction {
            get {
                return ((bool)(this["ModerateUsersAction"]));
            }
            set {
                this["ModerateUsersAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ModerateUserLearnMsgs {
            get {
                return ((bool)(this["ModerateUserLearnMsgs"]));
            }
            set {
                this["ModerateUserLearnMsgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int TwitchFollowerMsgLimit {
            get {
                return ((int)(this["TwitchFollowerMsgLimit"]));
            }
            set {
                this["TwitchFollowerMsgLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchFollowerAutoBanBots {
            get {
                return ((bool)(this["TwitchFollowerAutoBanBots"]));
            }
            set {
                this["TwitchFollowerAutoBanBots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int TwitchFollowerAutoBanCount {
            get {
                return ((int)(this["TwitchFollowerAutoBanCount"]));
            }
            set {
                this["TwitchFollowerAutoBanCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchFollowerEnableMsgLimit {
            get {
                return ((bool)(this["TwitchFollowerEnableMsgLimit"]));
            }
            set {
                this["TwitchFollowerEnableMsgLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MediaOverlayEnabled {
            get {
                return ((bool)(this["MediaOverlayEnabled"]));
            }
            set {
                this["MediaOverlayEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MediaOverlayChannelPoints {
            get {
                return ((bool)(this["MediaOverlayChannelPoints"]));
            }
            set {
                this["MediaOverlayChannelPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ManageClearButtonEnabled {
            get {
                return ((bool)(this["ManageClearButtonEnabled"]));
            }
            set {
                this["ManageClearButtonEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MediaOverlayAutoStart {
            get {
                return ((bool)(this["MediaOverlayAutoStart"]));
            }
            set {
                this["MediaOverlayAutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MsgSendSOToChat {
            get {
                return ((bool)(this["MsgSendSOToChat"]));
            }
            set {
                this["MsgSendSOToChat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MediaOverlayHelpExpand {
            get {
                return ((bool)(this["MediaOverlayHelpExpand"]));
            }
            set {
                this["MediaOverlayHelpExpand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MediaOverlayMRUPathSelect {
            get {
                return ((string)(this["MediaOverlayMRUPathSelect"]));
            }
            set {
                this["MediaOverlayMRUPathSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MediaOverlayShoutoutClips {
            get {
                return ((bool)(this["MediaOverlayShoutoutClips"]));
            }
            set {
                this["MediaOverlayShoutoutClips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AppCurrWorkingPopup {
            get {
                return ((bool)(this["AppCurrWorkingPopup"]));
            }
            set {
                this["AppCurrWorkingPopup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AppCurrWorkingAppData {
            get {
                return ((bool)(this["AppCurrWorkingAppData"]));
            }
            set {
                this["AppCurrWorkingAppData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchPubSubOnlineMode {
            get {
                return ((bool)(this["TwitchPubSubOnlineMode"]));
            }
            set {
                this["TwitchPubSubOnlineMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int RepeatUserMinutes {
            get {
                return ((int)(this["RepeatUserMinutes"]));
            }
            set {
                this["RepeatUserMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RepeatUserCount {
            get {
                return ((int)(this["RepeatUserCount"]));
            }
            set {
                this["RepeatUserCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int RepeatChatMinutes {
            get {
                return ((int)(this["RepeatChatMinutes"]));
            }
            set {
                this["RepeatChatMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int RepeatChatCount {
            get {
                return ((int)(this["RepeatChatCount"]));
            }
            set {
                this["RepeatChatCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RepeatAboveUserCount {
            get {
                return ((bool)(this["RepeatAboveUserCount"]));
            }
            set {
                this["RepeatAboveUserCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RepeatAboveChatCount {
            get {
                return ((bool)(this["RepeatAboveChatCount"]));
            }
            set {
                this["RepeatAboveChatCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RepeatUseThresholds {
            get {
                return ((bool)(this["RepeatUseThresholds"]));
            }
            set {
                this["RepeatUseThresholds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RepeatNoAdjustment {
            get {
                return ((bool)(this["RepeatNoAdjustment"]));
            }
            set {
                this["RepeatNoAdjustment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchClipConnectOnline {
            get {
                return ((bool)(this["TwitchClipConnectOnline"]));
            }
            set {
                this["TwitchClipConnectOnline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchClipDisconnectOffline {
            get {
                return ((bool)(this["TwitchClipDisconnectOffline"]));
            }
            set {
                this["TwitchClipDisconnectOffline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchFollowerConnectOnline {
            get {
                return ((bool)(this["TwitchFollowerConnectOnline"]));
            }
            set {
                this["TwitchFollowerConnectOnline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchFollowerDisconnectOffline {
            get {
                return ((bool)(this["TwitchFollowerDisconnectOffline"]));
            }
            set {
                this["TwitchFollowerDisconnectOffline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ManageOverlayTicker {
            get {
                return ((bool)(this["ManageOverlayTicker"]));
            }
            set {
                this["ManageOverlayTicker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int ModeratorApprovalTimeout {
            get {
                return ((int)(this["ModeratorApprovalTimeout"]));
            }
            set {
                this["ModeratorApprovalTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MsgCommandNotFound {
            get {
                return ((bool)(this["MsgCommandNotFound"]));
            }
            set {
                this["MsgCommandNotFound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MediaOverlayLogExceptions {
            get {
                return ((bool)(this["MediaOverlayLogExceptions"]));
            }
            set {
                this["MediaOverlayLogExceptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MediaOverlayActionPort {
            get {
                return ((int)(this["MediaOverlayActionPort"]));
            }
            set {
                this["MediaOverlayActionPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MediaOverlayUseSameStyle {
            get {
                return ((bool)(this["MediaOverlayUseSameStyle"]));
            }
            set {
                this["MediaOverlayUseSameStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MediaOverlayAutoServerStart {
            get {
                return ((bool)(this["MediaOverlayAutoServerStart"]));
            }
            set {
                this["MediaOverlayAutoServerStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MsgSocialSeparate {
            get {
                return ((bool)(this["MsgSocialSeparate"]));
            }
            set {
                this["MsgSocialSeparate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MediaOverlayCSSExpandHelp {
            get {
                return ((bool)(this["MediaOverlayCSSExpandHelp"]));
            }
            set {
                this["MediaOverlayCSSExpandHelp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GridTabifyUserFollow {
            get {
                return ((bool)(this["GridTabifyUserFollow"]));
            }
            set {
                this["GridTabifyUserFollow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("950")]
        public int GridTabifyUserFollowWidth {
            get {
                return ((int)(this["GridTabifyUserFollowWidth"]));
            }
            set {
                this["GridTabifyUserFollowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GridTabifyStreamRaids {
            get {
                return ((bool)(this["GridTabifyStreamRaids"]));
            }
            set {
                this["GridTabifyStreamRaids"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("950")]
        public int GridTabifyStreamRaidsWidth {
            get {
                return ((int)(this["GridTabifyStreamRaidsWidth"]));
            }
            set {
                this["GridTabifyStreamRaidsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MediaOverlayTickerSingle {
            get {
                return ((bool)(this["MediaOverlayTickerSingle"]));
            }
            set {
                this["MediaOverlayTickerSingle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MediaOverlayTickerRotate {
            get {
                return ((bool)(this["MediaOverlayTickerRotate"]));
            }
            set {
                this["MediaOverlayTickerRotate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MediaOverlayTickerMarquee {
            get {
                return ((bool)(this["MediaOverlayTickerMarquee"]));
            }
            set {
                this["MediaOverlayTickerMarquee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MediaOverlayTickerMulti {
            get {
                return ((bool)(this["MediaOverlayTickerMulti"]));
            }
            set {
                this["MediaOverlayTickerMulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MediaOverlayTickerSelected {
            get {
                return ((string)(this["MediaOverlayTickerSelected"]));
            }
            set {
                this["MediaOverlayTickerSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MediaOverlayTickerStatic {
            get {
                return ((bool)(this["MediaOverlayTickerStatic"]));
            }
            set {
                this["MediaOverlayTickerStatic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MediaOverlayTickerRotateTime {
            get {
                return ((int)(this["MediaOverlayTickerRotateTime"]));
            }
            set {
                this["MediaOverlayTickerRotateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int MediaOverlayTickerMarqueeTime {
            get {
                return ((int)(this["MediaOverlayTickerMarqueeTime"]));
            }
            set {
                this["MediaOverlayTickerMarqueeTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MediaOverlayTickerPort {
            get {
                return ((int)(this["MediaOverlayTickerPort"]));
            }
            set {
                this["MediaOverlayTickerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MediaOverlayStartWithStream {
            get {
                return ((bool)(this["MediaOverlayStartWithStream"]));
            }
            set {
                this["MediaOverlayStartWithStream"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ThemeLight {
            get {
                return ((bool)(this["ThemeLight"]));
            }
            set {
                this["ThemeLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ThemeDark {
            get {
                return ((bool)(this["ThemeDark"]));
            }
            set {
                this["ThemeDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableDebugLogOverlays {
            get {
                return ((bool)(this["EnableDebugLogOverlays"]));
            }
            set {
                this["EnableDebugLogOverlays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableDebugDataManager {
            get {
                return ((bool)(this["EnableDebugDataManager"]));
            }
            set {
                this["EnableDebugDataManager"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableDebugTwitchChatBot {
            get {
                return ((bool)(this["EnableDebugTwitchChatBot"]));
            }
            set {
                this["EnableDebugTwitchChatBot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableDebugTwitchClipBot {
            get {
                return ((bool)(this["EnableDebugTwitchClipBot"]));
            }
            set {
                this["EnableDebugTwitchClipBot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableDebugTwitchLiveBot {
            get {
                return ((bool)(this["EnableDebugTwitchLiveBot"]));
            }
            set {
                this["EnableDebugTwitchLiveBot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableDebugTwitchFollowBot {
            get {
                return ((bool)(this["EnableDebugTwitchFollowBot"]));
            }
            set {
                this["EnableDebugTwitchFollowBot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableDebugTwitchPubSubBot {
            get {
                return ((bool)(this["EnableDebugTwitchPubSubBot"]));
            }
            set {
                this["EnableDebugTwitchPubSubBot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableDebugDiscordBot {
            get {
                return ((bool)(this["EnableDebugDiscordBot"]));
            }
            set {
                this["EnableDebugDiscordBot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableManageDataOptions {
            get {
                return ((bool)(this["EnableManageDataOptions"]));
            }
            set {
                this["EnableManageDataOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public int GameBlackJackHouseStands {
            get {
                return ((int)(this["GameBlackJackHouseStands"]));
            }
            set {
                this["GameBlackJackHouseStands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int GameBlackJackPayoutDealt21 {
            get {
                return ((int)(this["GameBlackJackPayoutDealt21"]));
            }
            set {
                this["GameBlackJackPayoutDealt21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int GameBlackJackPayoutReach21 {
            get {
                return ((int)(this["GameBlackJackPayoutReach21"]));
            }
            set {
                this["GameBlackJackPayoutReach21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int GameBlackJackPayoutUnder21 {
            get {
                return ((int)(this["GameBlackJackPayoutUnder21"]));
            }
            set {
                this["GameBlackJackPayoutUnder21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You won #value currency!")]
        public string GameBlackJackPayoutMessage {
            get {
                return ((string)(this["GameBlackJackPayoutMessage"]));
            }
            set {
                this["GameBlackJackPayoutMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/WrithemTwine/TwineChatBot/releases/latest")]
        public string GitHubCheckStable {
            get {
                return ((string)(this["GitHubCheckStable"]));
            }
            set {
                this["GitHubCheckStable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExpanderBotUsageInfo {
            get {
                return ((bool)(this["ExpanderBotUsageInfo"]));
            }
            set {
                this["ExpanderBotUsageInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchStreamerOauthRefreshToken {
            get {
                return ((string)(this["TwitchStreamerOauthRefreshToken"]));
            }
            set {
                this["TwitchStreamerOauthRefreshToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TwitchTokenUseImplicit {
            get {
                return ((int)(this["TwitchTokenUseImplicit"]));
            }
            set {
                this["TwitchTokenUseImplicit"] = value;
            }
        }
                
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchTokenUseAuth {
            get {
                return ((bool)(this["TwitchTokenUseAuth"]));
            }
            set {
                this["TwitchTokenUseAuth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchAuthBotAccessToken {
            get {
                return ((string)(this["TwitchAuthBotAccessToken"]));
            }
            set {
                this["TwitchAuthBotAccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchAuthBotRefreshToken {
            get {
                return ((string)(this["TwitchAuthBotRefreshToken"]));
            }
            set {
                this["TwitchAuthBotRefreshToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchAuthBotClientSecret {
            get {
                return ((string)(this["TwitchAuthBotClientSecret"]));
            }
            set {
                this["TwitchAuthBotClientSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchAuthStreamerAccessToken {
            get {
                return ((string)(this["TwitchAuthStreamerAccessToken"]));
            }
            set {
                this["TwitchAuthStreamerAccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchAuthStreamerRefreshToken {
            get {
                return ((string)(this["TwitchAuthStreamerRefreshToken"]));
            }
            set {
                this["TwitchAuthStreamerRefreshToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchAuthStreamerClientSecret {
            get {
                return ((string)(this["TwitchAuthStreamerClientSecret"]));
            }
            set {
                this["TwitchAuthStreamerClientSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchStreamerRefreshToken {
            get {
                return ((string)(this["TwitchStreamerRefreshToken"]));
            }
            set {
                this["TwitchStreamerRefreshToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchAuthBotAuthCode {
            get {
                return ((string)(this["TwitchAuthBotAuthCode"]));
            }
            set {
                this["TwitchAuthBotAuthCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchAuthStreamerAuthCode {
            get {
                return ((string)(this["TwitchAuthStreamerAuthCode"]));
            }
            set {
                this["TwitchAuthStreamerAuthCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:3000")]
        public string TwitchAuthRedirectURL {
            get {
                return ((string)(this["TwitchAuthRedirectURL"]));
            }
            set {
                this["TwitchAuthRedirectURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TwitchAuthNewScopeRefresh {
            get {
                return ((bool)(this["TwitchAuthNewScopeRefresh"]));
            }
            set {
                this["TwitchAuthNewScopeRefresh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("From Twitch for registered application")]
        public string TwitchAuthClientId {
            get {
                return ((string)(this["TwitchAuthClientId"]));
            }
            set {
                this["TwitchAuthClientId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("From Twitch for registered application")]
        public string TwitchAuthStreamerClientId {
            get {
                return ((string)(this["TwitchAuthStreamerClientId"]));
            }
            set {
                this["TwitchAuthStreamerClientId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TwitchAuthUseInternalBrowser {
            get {
                return ((bool)(this["TwitchAuthUseInternalBrowser"]));
            }
            set {
                this["TwitchAuthUseInternalBrowser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableDebugTwitchTokenBot {
            get {
                return ((bool)(this["EnableDebugTwitchTokenBot"]));
            }
            set {
                this["EnableDebugTwitchTokenBot"] = value;
            }
        }
    }
}
