using StreamerBotLib.DataSQL;
using StreamerBotLib.DataSQL.Models;
using StreamerBotLib.Enums;
using StreamerBotLib.Events;
using StreamerBotLib.Models;
using StreamerBotLib.Overlay.Enums;
using StreamerBotLib.Overlay.Models;

using System.Collections.ObjectModel;
using System.Data;

namespace StreamerBotLib.Interfaces
{
    public interface IDataManager : IDataManagerReadOnly
    {
        event EventHandler<OnBulkFollowersAddFinishedEventArgs> OnBulkFollowersAddFinished;
        event EventHandler<OnDataCollectionUpdatedEventArgs> OnDataCollectionUpdated;

        bool CheckCurrency(LiveUser User, double value, string CurrencyName, SQLDBContext Refcontext = null);
        new bool CheckField(string table, string field, SQLDBContext Refcontext = null);
        new bool CheckFollower(string User, SQLDBContext Refcontext = null);
        new bool CheckFollower(string User, DateTime ToDateTime, SQLDBContext Refcontext = null);
        Tuple<string, string> CheckModApprovalRule(ModActionType modActionType, string ModAction, SQLDBContext Refcontext = null);
        bool CheckMultiStreams(DateTime streamStart, SQLDBContext Refcontext = null);
        new bool CheckPermission(string cmd, ViewerTypes permission, SQLDBContext Refcontext = null);
        new bool CheckShoutName(string UserId, SQLDBContext Refcontext = null);
        bool CheckStreamTime(DateTime CurrTime, SQLDBContext Refcontext = null);
        new bool CheckUser(LiveUser User, SQLDBContext Refcontext = null);
        new bool CheckUser(LiveUser User, DateTime ToDateTime, SQLDBContext Refcontext = null);
        string CheckWelcomeUser(string User, SQLDBContext Refcontext = null);
        void ClearAllCurrencyValues(SQLDBContext Refcontext = null);
        void ClearUsersNotFollowers(SQLDBContext Refcontext = null);
        void ClearWatchTime(SQLDBContext Refcontext = null);
        void DeleteDataRows(IEnumerable<DataRow> dataRows, SQLDBContext Refcontext = null);
        string EditCommand(string cmd, List<string> Arglist, SQLDBContext Refcontext = null);
        Tuple<ModActions, Enums.BanReasons, int> FindRemedy(ViewerTypes viewerTypes, MsgTypes msgTypes, SQLDBContext Refcontext = null);
        Task<ObservableCollection<DataSQL.Models.BanReasons>> GetBanReasonsLocalObservable();
        Task<ObservableCollection<BanRules>> GetBanRulesLocalObservable();
        Task<ObservableCollection<CategoryList>> GetCategoryListLocalObservable();
        Task<ObservableCollection<ChannelEvents>> GetChannelEventsLocalObservable();
        Task<ObservableCollection<Clips>> GetClipsLocalObservable();
        new CommandData GetCommand(string cmd, SQLDBContext Refcontext = null);
        new IEnumerable<string> GetCommandList(bool prefix = true, SQLDBContext Refcontext = null);
        new string GetCommandString(SQLDBContext Refcontext = null);
        Task<ObservableCollection<Commands>> GetCommandsLocalObservable();
        Task<ObservableCollection<CommandsUser>> GetCommandsUserLocalObservable();
        Task<ObservableCollection<Currency>> GetCurrencyLocalObservable();
        new List<string> GetCurrencyNames(SQLDBContext Refcontext = null);
        Task<ObservableCollection<DataSQL.Models.CurrencyType>> GetCurrencyTypeLocalObservable();
        Task<ObservableCollection<CustomWelcome>> GetCustomWelcomeLocalObservable();
        int GetDeathCounter(string currCategory, SQLDBContext Refcontext = null);
        new string GetEventRowData(ChannelEventActions rowcriteria, out bool Enabled, out short Multi, SQLDBContext Refcontext = null);
        int GetFollowerCount(SQLDBContext Refcontext = null);
        Task<ObservableCollection<Followers>> GetFollowersLocalObservable();
        new List<CategoryData> GetGameCategories(SQLDBContext Refcontext = null);
        Task<ObservableCollection<GameDeadCounter>> GetGameDeadCounterLocalObservable();
        Task<ObservableCollection<GiveawayUserData>> GetGiveawayUserDataLocalObservable();
        Task<ObservableCollection<InRaidData>> GetInRaidDataLocalObservable();
        new string GetKey(string Table, SQLDBContext Refcontext = null);
        new IEnumerable<string> GetKeys(string Table, SQLDBContext Refcontext = null);
        Task<ObservableCollection<LearnMsgs>> GetLearnMsgsLocalObservable();
        Task<ObservableCollection<ModeratorApprove>> GetModeratorApproveLocalObservable();
        new ObservableCollection<ArchiveMultiStream> GetCleanupList();
        Task<ObservableCollection<MultiChannels>> GetMultiChannelsLocalObservable();
        Task<ObservableCollection<MultiLiveStreams>> GetMultiLiveStreamsLocalObservable();
        Task<ObservableCollection<MultiWebhooks>> GetMultiWebhooksLocalObservable();
        Task<ObservableCollection<MultiSummaryLiveStreams>> GetMultiSummaryLiveStreamsLocalObservable();
        string GetNewestFollower(SQLDBContext Refcontext = null);
        Task<ObservableCollection<OldFollowUsers>> GetOldFollowUsersLocalObservable();
        Task<ObservableCollection<OutRaidData>> GetOutRaidDataLocalObservable();
        Dictionary<string, List<string>> GetOverlayActions(SQLDBContext Refcontext = null);
        List<OverlayActionType> GetOverlayActions(OverlayTypes overlayType, string overlayAction, string username, SQLDBContext Refcontext = null);
        Task<ObservableCollection<OverlayServices>> GetOverlayServicesLocalObservable();
        Task<ObservableCollection<OverlayTicker>> GetOverlayTickerLocalObservable();
        string GetQuote(int QuoteNum, SQLDBContext Refcontext = null);
        int GetQuoteCount(SQLDBContext Refcontext = null);
        Task<ObservableCollection<Quotes>> GetQuotesLocalObservable();
        Task<ObservableCollection<ShoutOuts>> GetShoutOutsLocalObservable();
        List<string> GetSocialComs(SQLDBContext Refcontext = null);
        new string GetSocials(SQLDBContext Refcontext = null);
        StreamStat GetStreamData(DateTime dateTime, SQLDBContext Refcontext = null);
        Task<ObservableCollection<StreamStats>> GetStreamStatsLocalObservable();
        new List<string> GetTableFields(string TableName, SQLDBContext Refcontext = null);
        new List<string> GetTableNames(SQLDBContext Refcontext = null);
        List<TickerItem> GetTickerItems(SQLDBContext Refcontext = null);
        new Tuple<string, int, List<string>> GetTimerCommand(string Cmd, SQLDBContext Refcontext = null);
        new List<Tuple<string, int, List<string>>> GetTimerCommands(SQLDBContext Refcontext = null);
        new int GetTimerCommandTime(string Cmd, SQLDBContext Refcontext = null);
        new string GetUsage(string command, SQLDBContext Refcontext = null);
        new string GetUserId(LiveUser User, SQLDBContext Refcontext = null);
        Task<ObservableCollection<Users>> GetUsersLocalObservable();
        Task<ObservableCollection<UserStats>> GetUserStatsLocalObservable();
        new List<Tuple<bool, Uri>> GetWebhooks(WebhooksSource webhooksSource, WebhooksKind webhooks, SQLDBContext Refcontext = null);
        Task<ObservableCollection<Webhooks>> GetWebhooksLocalObservable();
        void Initialize(SQLDBContext Refcontext = null);
        object[] PerformQuery(CommandsBase row, int Top = 0, SQLDBContext Refcontext = null);
        object PerformQuery(CommandsBase row, string ParamValue, SQLDBContext Refcontext = null);
        bool PostCategory(CategoryData categoryData, SQLDBContext Refcontext = null);
        public void PostCategoryStream(CategoryData category, int StreamCount = 0, SQLDBContext Refcontext = null);
        bool PostClip(string ClipId, DateTime CreatedAt, decimal Duration, string GameId, string Language, string Title, string Url, string fromUserId, string fromUserName, SQLDBContext Refcontext = null);
        string PostCommand(string cmd, CommandParams Params, SQLDBContext Refcontext = null);
        void PostCurrencyUpdate(LiveUser User, double value, string CurrencyName, SQLDBContext Refcontext = null);
        int PostDeathCounterUpdate(string currCategory, bool Reset = false, int updateValue = 1, SQLDBContext Refcontext = null);
        bool PostFollower(Follow follow, SQLDBContext Refcontext = null);
        void PostGiveawayData(string UserId, DateTime dateTime, SQLDBContext Refcontext = null);
        public void PostInRaidData(LiveUser user, DateTime time, int viewers, CategoryData gamename, SQLDBContext Refcontext = null);
        void PostLearnMsgsRow(string Message, MsgTypes MsgType, SQLDBContext Refcontext = null);
        bool PostMergeUserStats(string CurrUser, string SourceUser, Platform platform, SQLDBContext Refcontext = null);
        void PostMonitorChannel(IEnumerable<LiveUser> liveUsers, SQLDBContext Refcontext = null);
        bool PostMultiStreamDate(string userid, string username, Platform platform, DateTime onDate, SQLDBContext Refcontext = null);
        void PostNewAutoShoutUser(string UserId, Platform platform, SQLDBContext Refcontext = null);
        void PostOutgoingRaid(string HostedChannel, DateTime dateTime, SQLDBContext Refcontext = null);
        int PostQuote(string Text, SQLDBContext Refcontext = null);
        void PostStreamStat(StreamStat streamStat, SQLDBContext Refcontext = null);
        void PostUserCustomWelcome(LiveUser User, string WelcomeMsg, SQLDBContext Refcontext = null);
        void RemoveAllFollowers(SQLDBContext Refcontext = null);
        void RemoveAllGiveawayData(SQLDBContext Refcontext = null);
        void RemoveAllInRaidData(SQLDBContext Refcontext = null);
        void RemoveAllOutRaidData(SQLDBContext Refcontext = null);
        void RemoveAllOverlayTickerData(SQLDBContext Refcontext = null);
        void RemoveAllStreamStats(SQLDBContext Refcontext = null);
        void RemoveAllUsers(SQLDBContext Refcontext = null);
        bool RemoveCommand(string command, SQLDBContext Refcontext = null);
        bool RemoveQuote(int QuoteNum, SQLDBContext Refcontext = null);
        void SetBuiltInCommandsEnabled(bool Enabled, SQLDBContext Refcontext = null);
        void SetIsEnabled(IEnumerable<DataRow> dataRows, bool IsEnabled = false, SQLDBContext Refcontext = null);
        void SetSystemEventsEnabled(bool Enabled, SQLDBContext Refcontext = null);
        void SetUserDefinedCommandsEnabled(bool Enabled, SQLDBContext Refcontext = null);
        void SetWebhooksEnabled(bool Enabled, SQLDBContext Refcontext = null);
        void StartBulkFollowers(SQLDBContext Refcontext = null);
        void SummarizeStreamData(SQLDBContext Refcontext = null);
        void SummarizeStreamData(ArchiveMultiStream archiveRecord, SQLDBContext Refcontext = null);
        void UpdateCurrency(List<string> Users, DateTime dateTime, SQLDBContext Refcontext = null);
        void UpdateFollowers(IEnumerable<Follow> follows, SQLDBContext Refcontext = null);
        new List<LearnMsgRecord> UpdateLearnedMsgs(SQLDBContext Refcontext = null);
        void UpdateOverlayTicker(OverlayTickerItem item, string name, SQLDBContext Refcontext = null);
        void UpdateStats(DBUserStats Stat, string userId, Platform platform, SQLDBContext Refcontext = null);
        void UpdateWatchTime(List<LiveUser> Users, DateTime CurrTime, SQLDBContext Refcontext = null);
        void UpdateWatchTime(LiveUser User, DateTime CurrTime, SQLDBContext Refcontext = null);
        void UserJoined(LiveUser User, DateTime NowSeen, SQLDBContext Refcontext = null);
        void UserJoined(IEnumerable<LiveUser> Users, DateTime NowSeen, SQLDBContext Refcontext = null);
        void UserLeft(LiveUser User, DateTime LastSeen, SQLDBContext Refcontext = null);
        void NotifyStopBulkFollowers(SQLDBContext Refcontext = null);
        IEnumerable<Follow> PostFollowers(IEnumerable<Follow> follows, SQLDBContext Refcontext = null);
        void GUIRowEditSave(SQLDBContext Refcontext = null);
        bool PostStream(DateTime StreamStart, string Category, SQLDBContext Refcontext = null);

        void PostDataGridGUIAddRow(IDatabaseTableMeta tableMeta, SQLDBContext Refcontext = null);
        void PostMultiLiveLog(string LogItem, SQLDBContext Refcontext = null);
        void PostCurrencyUpdate(List<PlayGameUserWager<PlayingCardFrench, PlayingCardSuit>> Updates, string CurrencyName, SQLDBContext Refcontext = null);
    }
}