using StreamerBotLib.Data;
using StreamerBotLib.Enums;
using StreamerBotLib.Models;
using StreamerBotLib.Overlay.Enums;
using StreamerBotLib.Overlay.Models;

using System.Data;

namespace StreamerBotLib.Interfaces
{
    public interface IDataManager
    {
        bool UpdatingFollowers { get; set; }
        bool CheckCurrency(LiveUser User, double value, string CurrencyName);
        bool CheckField(string table, string field);
        bool CheckFollower(string User);
        bool CheckFollower(string User, DateTime ToDateTime);
        Tuple<string, string> CheckModApprovalRule(ModActionType modActionType, string ModAction);
        bool CheckMultiStreams(DateTime dateTime);
        bool CheckPermission(string cmd, ViewerTypes permission);
        bool CheckShoutName(string UserName);
        bool CheckStreamTime(DateTime CurrTime);
        bool CheckUser(LiveUser User);
        bool CheckUser(LiveUser User, DateTime ToDateTime);
        string CheckWelcomeUser(string User);
        void ClearAllCurrencyValues();
        void ClearUsersNotFollowers();
        void ClearWatchTime();
        void DeleteDataRows(IEnumerable<DataRow> dataRows);
        string EditCommand(string cmd, List<string> Arglist);
        Tuple<ModActions, BanReasons, int> FindRemedy(ViewerTypes viewerTypes, MsgTypes msgTypes);
        CommandData GetCommand(string cmd);
        IEnumerable<string> GetCommandList();
        string GetCommands();
        List<string> GetCurrencyNames();
        int GetDeathCounter(string currCategory);
        string GetEventRowData(ChannelEventActions rowcriteria, out bool Enabled, out ushort Multi);
        int? GetFollowerCount();
        List<Tuple<string, string>> GetGameCategories();
        string GetKey(string Table);
        IEnumerable<string> GetKeys(string Table);
        string GetNewestFollower();
        List<OverlayActionType> GetOverlayActions(string overlayType, string overlayAction, string username);
        Dictionary<string, List<string>> GetOverlayActions();
        string GetQuote(int QuoteNum);
        int GetQuoteCount();
        List<object> GetRowsDataColumn(string dataTable, string dataColumn);
        List<string> GetSocialComs();
        string GetSocials();
        StreamStat GetStreamData(DateTime dateTime);
        List<string> GetTableFields(string TableName);
        List<string> GetTableNames();
        List<TickerItem> GetTickerItems();
        Tuple<string, uint, string[]> GetTimerCommand(string Cmd);
        List<Tuple<string, uint, string[]>> GetTimerCommands();
        int? GetTimerCommandTime(string Cmd);
        string GetUsage(string command);
        string GetUserId(LiveUser User);
        List<Tuple<bool, Uri>> GetWebhooks(WebhooksKind webhooks);
        void Initialize();
        void NotifySaveData();
        object[] PerformQuery(CommandData row, uint Top = 0);
        object PerformQuery(CommandData row, string ParamValue);
        bool PostCategory(string CategoryId, string newCategory);
        bool PostClip(string ClipId, string CreatedAt, float Duration, string GameId, string Language, string Title, string Url);
        string PostCommand(string cmd, CommandParams Params);
        void PostCurrencyRows();
        void PostCurrencyRows(ref DataSource.UsersRow usersRow);
        void PostCurrencyUpdate(LiveUser User, double value, string CurrencyName);
        int PostDeathCounterUpdate(string currCategory, bool Reset = false, uint updateValue = 1);
        bool PostFollower(LiveUser User, DateTime FollowedDate, string Category);
        void PostGiveawayData(string DisplayName, DateTime dateTime);
        void PostInRaidData(string user, DateTime time, string viewers, string gamename);
        void PostLearnMsgsRow(string Message, MsgTypes MsgType);
        bool PostMergeUserStats(string CurrUser, string SourceUser, Platform platform);
        void PostNewAutoShoutUser(string UserName, string UserId, string platform);
        void PostOutgoingRaid(string HostedChannel, DateTime dateTime);
        int PostQuote(string Text);
        bool PostStream(DateTime StreamStart);
        void PostStreamStat(StreamStat streamStat);
        void PostUpdatedDataRow(bool RowChanged);
        void PostUserCustomWelcome(string User, string WelcomeMsg);
        void RemoveAllFollowers();
        void RemoveAllGiveawayData();
        void RemoveAllInRaidData();
        void RemoveAllOutRaidData();
        void RemoveAllOverlayTickerData();
        void RemoveAllStreamStats();
        void RemoveAllUsers();
        bool RemoveCommand(string command);
        bool RemoveQuote(int QuoteNum);
        void SetBuiltInCommandsEnabled(bool Enabled);
        void SetWebhooksEnabled(bool Enabled);
        void SetIsEnabled(IEnumerable<DataRow> dataRows, bool IsEnabled = false);
        void SetSystemEventsEnabled(bool Enabled);
        void SetUserDefinedCommandsEnabled(bool Enabled);
        void StartBulkFollowers();
        void StopBulkFollows();
        bool TestInRaidData(string user, DateTime time, string viewers, string gamename);
        bool TestOutRaidData(string HostedChannel, DateTime dateTime);
        void UpdateCurrency(List<string> Users, DateTime dateTime);
        void UpdateFollowers(IEnumerable<Follow> follows, string Category);
        List<LearnMsgRecord> UpdateLearnedMsgs();
        void UpdateOverlayTicker(OverlayTickerItem item, string name);
        void UpdateWatchTime(List<string> Users, DateTime CurrTime);
        void UpdateWatchTime(string User, DateTime CurrTime);
        void UserJoined(LiveUser User, DateTime NowSeen);
        void UserLeft(LiveUser User, DateTime LastSeen);
    }
}