using StreamerBotLib.DataSQL.Models;
using StreamerBotLib.Enums;
using StreamerBotLib.Events;
using StreamerBotLib.Models;
using StreamerBotLib.Overlay.Enums;
using StreamerBotLib.Overlay.Models;

using System.Data;

namespace StreamerBotLib.Interfaces
{
    public interface IDataManager : IDataManagerReadOnly
    {
        event EventHandler<OnBulkFollowersAddFinishedEventArgs> OnBulkFollowersAddFinished;
        event EventHandler<OnDataCollectionUpdatedEventArgs> OnDataCollectionUpdated;
        event EventHandler<EventArgs> OnLoadCompleted;

        bool CheckCurrency(LiveUser User, double value, string CurrencyName);
        new bool CheckField(string table, string field);
        new bool CheckFollower(string User);
        new bool CheckFollower(string User, DateTime ToDateTime);
        Tuple<string, string> CheckModApprovalRule(ModActionType modActionType, string ModAction);
        bool CheckMultiStreams(DateTime streamStart);
        new bool CheckPermission(string cmd, ViewerTypes permission);
        new bool CheckShoutName(string UserId);
        bool CheckStreamTime(DateTime CurrTime);
        new bool CheckUser(LiveUser User);
        new bool CheckUser(LiveUser User, DateTime ToDateTime);
        string CheckWelcomeUser(string User);
        void ClearAllCurrencyValues();
        void ClearUsersNotFollowers();
        void ClearWatchTime();
        void DeleteDataRows(IEnumerable<DataRow> dataRows);
        string EditCommand(string cmd, List<string> Arglist);
        Tuple<ModActions, Enums.BanReasons, int> FindRemedy(ViewerTypes viewerTypes, MsgTypes msgTypes);
        new CommandData GetCommand(string cmd);
        new IEnumerable<string> GetCommandList(bool prefix = true);
        new string GetCommandString();
        new List<string> GetCurrencyNames();
        int GetDeathCounter(string currCategory);
        new string GetEventRowData(ChannelEventActions rowcriteria, out bool Enabled, out short Multi);
        int GetFollowerCount();
        new List<CategoryData> GetGameCategories();
        new string GetKey(string Table);
        new IEnumerable<string> GetKeys(string Table);
        new List<ArchiveMultiStream> GetCleanupList();
        string GetNewestFollower();
        Dictionary<string, List<string>> GetOverlayActions();
        List<OverlayActionType> GetOverlayActions(OverlayTypes overlayType, string overlayAction, string username);
        string GetQuote(int QuoteNum);
        int GetQuoteCount();
        List<string> GetSocialComs();
        new string GetSocials();
        StreamStat GetStreamData(DateTime dateTime);
        new List<string> GetTableFields(string TableName);
        new List<string> GetTableNames();
        List<TickerItem> GetTickerItems();
        new Tuple<string, int, List<string>> GetTimerCommand(string Cmd);
        new List<Tuple<string, int, List<string>>> GetTimerCommands();
        new int GetTimerCommandTime(string Cmd);
        new string GetUsage(string command);
        new string GetUserId(LiveUser User);
        new List<Tuple<bool, Uri>> GetWebhooks(WebhooksSource webhooksSource, WebhooksKind webhooks);
        void Initialize();
        object[] PerformQuery(CommandsBase row, int Top = 0);
        object PerformQuery(CommandsBase row, string ParamValue);
        bool PostCategory(CategoryData categoryData);
        public void PostCategoryStream(CategoryData category, int StreamCount = 0);
        bool PostClip(string ClipId, DateTime CreatedAt, decimal Duration, string GameId, string Language, string Title, string Url, string fromUserId, string fromUserName);
        string PostCommand(string cmd, CommandParams Params);
        void PostCurrencyType(DataSQL.Models.CurrencyType currencyType);
        void PostCurrencyUpdate(LiveUser User, double value, string CurrencyName);
        int PostDeathCounterUpdate(string currCategory, bool Reset = false, int updateValue = 1);
        bool PostFollower(Follow follow);
        void PostGiveawayData(string UserId, DateTime dateTime);
        public void PostInRaidData(LiveUser user, DateTime time, int viewers, CategoryData gamename);
        void PostLearnMsgsRow(string Message, MsgTypes MsgType);
        bool PostMergeUserStats(string CurrUser, string SourceUser, Platform platform);
        void PostMonitorChannel(IEnumerable<LiveUser> liveUsers);
        bool PostMultiStreamDate(LiveUser liveUser, DateTime onDate);
        void PostNewAutoShoutUser(string UserId, Platform platform);
        void PostOutgoingRaid(string HostedChannel, DateTime dateTime);
        int PostQuote(string Text);
        void PostStreamStat(StreamStat streamStat);
        void PostUserCustomWelcome(LiveUser User, string WelcomeMsg);
        void RemoveAllFollowers();
        void RemoveAllGiveawayData();
        void RemoveAllInRaidData();
        void RemoveAllOutRaidData();
        void RemoveAllOverlayTickerData();
        void RemoveAllStreamStats();
        void RemoveAllUsers();
        bool RemoveCommand(string command);
        bool RemoveQuote(int QuoteNum);
        void SetBuiltInCommandsEnabled(bool Enabled);
        void SetIsEnabled(IEnumerable<DataRow> dataRows, bool IsEnabled = false);
        void SetSystemEventsEnabled(bool Enabled);
        void SetUserDefinedCommandsEnabled(bool Enabled);
        void SetWebhooksEnabled(bool Enabled);
        void StartBulkFollowers();
        void SummarizeStreamData();
        void SummarizeStreamData(ArchiveMultiStream archiveRecord);
        void UpdateCurrency(List<LiveUser> Users, DateTime dateTime);
        void UpdateFollowers(IEnumerable<Follow> follows);
        new List<LearnMsgRecord> UpdateLearnedMsgs();
        void UpdateOverlayTicker(OverlayTickerItem item, string name);
        void UpdateStats(DBUserStats Stat, string userId, Platform platform);
        void UpdateWatchTime(List<LiveUser> Users, DateTime CurrTime);
        void UserJoined(IEnumerable<LiveUser> Users, DateTime NowSeen);
        void UserLeft(LiveUser User, DateTime LastSeen);
        void NotifyStopBulkFollowers();
        IEnumerable<Follow> PostFollowers(IEnumerable<Follow> follows);
        void GUIRowEditSave();
        bool PostStream(DateTime StreamStart, string Category);

        void PostDataGridGUIAddRow(IDatabaseTableMeta tableMeta);
        void PostMultiLiveLog(string LogItem);
        void PostCurrencyUpdate(List<PlayGameUserWager<PlayingCardFrench, PlayingCardSuit>> Updates, string CurrencyName);
        object GetICollection(DataTables dataTable);
        void Exit();
    }
}