namespace StreamerBot.Enums
{
    public enum BotEvents
    {
        TwitchBeingHosted,
        TwitchBulkPostFollowers,
        TwitchStartBulkFollowers,
        TwitchStopBulkFollowers,
        TwitchCommunitySubscription,
        TwitchGiftSubscription,
        TwitchNewSubscriber,
        TwitchPostNewClip,
        TwitchClipSvcOnClipFound,
        TwitchPostNewFollowers,
        TwitchReSubscriber,
        TwitchStreamOffline,
        TwitchStreamOnline,
        TwitchStreamUpdate,
        TwitchCategoryUpdate,
        TwitchNowHosting,
        TwitchExistingUsers,
        TwitchOnUserJoined,
        TwitchOnUserLeft,
        TwitchOnUserTimedout,
        TwitchOnUserBanned,
        TwitchRitualNewChatter,
        TwitchMessageReceived,
        TwitchIncomingRaid,
        TwitchChatCommandReceived,
        TwitchChannelPointsRewardRedeemed
    }
}
