namespace StreamerBotLib.Enums
{
    public enum BotEvents
    {
        TwitchChatBotStarted,
        TwitchChatBotStopping,
        TwitchChatBotStopped,
        TwitchBeingHosted,
        TwitchBulkPostFollowers,
        TwitchStartBulkFollowers,
        TwitchStopBulkFollowers,
        TwitchCommunitySubscription,
        TwitchGiftSubscription,
        TwitchNewSubscriber,
        TwitchPostNewClip,
        TwitchClipSvcOnClipFound,
        TwitchPostNewFollowers,
        TwitchReSubscriber,
        TwitchStreamOffline,
        TwitchStreamOnline,
        TwitchStreamUpdate,
        TwitchCategoryUpdate,
        TwitchNowHosting,
        TwitchExistingUsers,
        TwitchOnUserJoined,
        TwitchOnUserLeft,
        TwitchOnUserTimedout,
        TwitchOnUserBanned,
        TwitchRitualNewChatter,
        TwitchMessageReceived,
        TwitchIncomingRaid,
        TwitchChatCommandReceived,
        TwitchChannelPointsRewardRedeemed,
        TwitchOutgoingRaid
    }
}
